import type { StreetDef, TenantProfile, StoryEvent } from '../core/types';
import { isWeekend } from '../core/game';
import { PAST_1995, tripIntro, tripOutro, pastLandmark } from './dongyuan1995';
import { PAST_1960, tripIntro1960, pastLandmark1960 } from './dongyuan1960';
import { PILGRIMAGE, pilgrimSteps, endingSteps } from './dongyuanPilgrim';
import { pilgrimageDone } from '../core/memory';
import { say, emote, narrate, focus, appear, leave, fx, effect, choice, opt, look } from './dsl';

/**
 * 東原老街（第四章）。2016 年：空屋、離鄉、遊客很少。
 * 所有角色都是虛構的；店種、味道、街景來自東原的生活記憶。
 */

const ST = 'dongyuan';
const T = (t: Omit<TenantProfile, 'street'>): TenantProfile => ({ ...t, street: ST });

const tenants: TenantProfile[] = [
  T({
    id: 'dy-meatball', name: '肉圓伯', shopName: '老街肉圓', shopType: 'meatball',
    traits: ['hardworking', 'veteran'], skill: 4, maxRentTier: 1,
    intro: '我這間肉圓，一年三百六十五天都開。颱風天也開。客人在等啊。',
    look: look({ skin: 0xc98e66, hair: 0xd9d4cc, hairStyle: 'short', shirt: 0xf0f0f0, pants: 0x3d3a36, accessory: 'apron', age: 'old' }),
    relations: { 'dy-lan': 30, 'dy-barber': 25 },
    arrive: { flag: 'never' },
    lines: {
      hello: '好，明天照常開。',
      happy: ['今天的肉圓蒸得剛剛好。', '有個囡仔從台北回來，第一站就來吃我的肉圓。'],
      unhappy: ['街上越來越安靜了……', '燈還亮著，就會有人來吧。'],
      idle: ['醬汁是用蒜頭跟糖慢慢熬的。', '以前這條街，晚上比白天還熱鬧。'],
      rival: ['做吃的，要老實。', '少年仔，慢慢來。'],
      friend: ['來，多加一顆。', '你小時候是不是常來？我記得你。'],
      refuse: '這個租金，我要賣幾千顆肉圓才付得起。',
    },
  }),
  T({
    id: 'dy-lan', name: '阿蘭', shopName: '阿蘭雜貨', shopType: 'grocery',
    traits: ['hardworking', 'friendly'], skill: 3, maxRentTier: 1,
    intro: '我嫁來東原十五年了。婆婆走了以後，雜貨店換我顧。她以前還開過冰店，四果冰跟冬瓜茶最有名喔。',
    look: look({ skin: 0xd9a27a, hair: 0x111111, hairStyle: 'long', shirt: 0xef8fb1, pants: 0x54627a, accessory: 'apron', age: 'mid' }),
    relations: { 'dy-meatball': 30 },
    arrive: { flag: 'never' },
    lines: {
      hello: '大家都叫我阿蘭，有缺什麼跟我說。',
      happy: ['今天好多阿嬤來買東西，還留下來聊天。', '我兒子說，長大要回來幫我顧店。'],
      unhappy: ['大賣場那麼方便，誰還來雜貨店……', '婆婆，對不起，生意不太好。'],
      idle: ['龍眼季的時候，我也會去焙灶幫忙。', '醬油、米、蚊香，這裡都有。'],
      rival: ['我也是東原人啊。', '來這麼久了，還要被說是外人嗎？'],
      friend: ['今天煮太多，拿去吃。', '你要的東西，我幫你留了。'],
      refuse: '這樣太貴了，雜貨店賺不了那麼多。',
    },
  }),
  T({
    id: 'dy-barber', name: '阿財師', shopName: '財記理髮', shopType: 'barber',
    traits: ['veteran', 'gossip'], skill: 3, maxRentTier: 1,
    intro: '以前街上有三間理髮店，現在剩我一間。整條街的秘密，都掉在我的地板上。',
    look: look({ skin: 0xe8b48f, hair: 0xb7b1a8, hairStyle: 'short', shirt: 0xf6f6f6, pants: 0x3d3a36, accessory: 'glasses', age: 'old' }),
    relations: { 'dy-meatball': 25 },
    arrive: { flag: 'never' },
    lines: {
      hello: '來，坐。要剪短一點嗎？',
      happy: ['今天剪了七顆頭，手都酸了！', '有個少年仔說要跟我學剪頭髮。'],
      unhappy: ['剪刀都快生鏽了。', '以前排隊排到門口，現在……'],
      idle: ['你知道嗎？以前那間戲院啊……算了，下次再說。', '頭髮剪完，人也輕鬆了。'],
      rival: ['我剪的頭，五十年沒人說不好看。', '少年仔，八卦不是這樣講的。'],
      friend: ['來，免費幫你修一下鬢角。', '我跟你說一個秘密……'],
      refuse: '這個價錢，我剪到退休都付不起。',
    },
  }),
  T({
    id: 'dy-cafe', name: '小宇', shopName: '樹屋咖啡', shopType: 'cafe',
    traits: ['creative', 'online'], skill: 3, maxRentTier: 1,
    intro: '我跟小穎是同一個大學團隊來的。計畫結束了，可是我們都不想走。想開一間咖啡店，讓來拍老屋的人有地方坐。',
    look: look({ skin: 0xf5d0b0, hair: 0x4a3324, hairStyle: 'spiky', shirt: 0x3fb2a9, pants: 0x54627a, accessory: 'none', age: 'young' }),
    relations: { 'dy-longan': 15 },
    lines: {
      hello: '耶！東原的第一間咖啡店！',
      happy: ['今天有攝影團坐滿整間店！', '有人在 IG 標記樹屋咖啡了！'],
      unhappy: ['平日一整天只賣三杯……', '阿嬤們說咖啡太苦了。'],
      idle: ['我在研究龍眼蜜拿鐵。', '週末單車隊會來喔。'],
      rival: ['我們只是想讓老街活過來啊。', '咖啡不是只有城市人在喝的。'],
      friend: ['請你喝一杯！', '一起來辦活動吧！'],
      refuse: '我們還是學生創業，這個價錢真的不行……',
    },
  }),
  T({
    id: 'dy-longan', name: '興伯', shopName: '柴焙龍眼乾', shopType: 'longan',
    traits: ['veteran', 'stubborn'], skill: 4, maxRentTier: 1,
    intro: '龍眼要用龍眼木焙三天三夜，中間要一直翻。機器烘的？那不叫龍眼乾。',
    look: look({ skin: 0xb07a52, hair: 0xd9d4cc, hairStyle: 'short', shirt: 0x6d5a4a, pants: 0x3d3a36, accessory: 'hat', age: 'old' }),
    relations: { 'dy-cafe': 15 },
    arrive: { minDay: 2 },
    lines: {
      hello: '好，龍眼乾放這裡賣。',
      happy: ['遊客說這是吃過最香的龍眼乾！', '今年的龍眼，焙得很好。'],
      unhappy: ['焙灶的煙，一年比一年少了。', '年輕人都不想做這種辛苦的工作。'],
      idle: ['焙龍眼要顧火，不能睡。', '窯那邊以前是戲院，你知道嗎？'],
      rival: ['機器烘的，沒有柴燒的香。', '做事情不能偷懶。'],
      friend: ['拿一包回去吃。', '下次焙龍眼，你來幫我顧火。'],
      refuse: '龍眼乾很重工，這個價錢不行。',
    },
  }),
  T({
    id: 'dy-baozi', name: '秀枝姨', shopName: '秀枝包子', shopType: 'baozi',
    traits: ['hardworking', 'hothead'], skill: 3, maxRentTier: 1,
    intro: '我阿母的包子店，後來搬進隔壁打鐵伯的舊舖子，一賣就是二十年。現在換我了：每天四點起來揉麵，東原的囡仔上學前都要吃我的包子，這是規矩。',
    look: look({ skin: 0xe8b48f, hair: 0x2a1d17, hairStyle: 'bun', shirt: 0xd35454, pants: 0x3d3a36, accessory: 'apron', age: 'mid' }),
    relations: { 'dy-mantou': -40 },
    arrive: { minDay: 3 },
    lines: {
      hello: '明天一早就有包子吃！',
      happy: ['蒸籠一開，阿公阿嬤都排隊了！', '舉重隊的孩子一次買二十顆！'],
      unhappy: ['麵粉又漲價了……', '早上都沒人經過。'],
      idle: ['高麗菜包是我的招牌。', '包子要趁熱吃。'],
      rival: ['炸饅頭？油膩膩的有什麼好吃！', '我的包子比你的饅頭有料多了！'],
      friend: ['多拿兩顆給你家孩子。', '明天幫你留一籠。'],
      refuse: '賣包子一顆才幾塊錢，付不起啦。',
    },
  }),
  T({
    id: 'dy-ribsoup', name: '阿豪', shopName: '豪記排骨酥湯', shopType: 'ribsoup',
    traits: ['creative', 'dramatic'], skill: 4, maxRentTier: 2,
    intro: '我在台南市區當了十年廚師。每次想家，就想到小時候巷口那碗排骨酥湯。所以我回來了！',
    look: look({ skin: 0xe8b48f, hair: 0x111111, hairStyle: 'short', shirt: 0xf0f0f0, pants: 0x2b2b2b, accessory: 'headband', age: 'young' }),
    arrive: { minDay: 5, minRep: 12 },
    lines: {
      hello: '回家的感覺真好！',
      happy: ['有阿伯喝完說：「就是這個味道！」我差點哭出來！', '單車隊整隊進來喝湯！'],
      unhappy: ['我是不是不該回來的……', '市區的同事都在笑我。'],
      idle: ['白蘿蔔要燉到透明。', '排骨酥要先炸再燉。'],
      rival: ['我的湯，是用心熬的！', '你有試過燉十個小時嗎？'],
      friend: ['來，幫你加一塊排骨酥！', '收店後一起吃宵夜！'],
      refuse: '剛回來創業，這個價錢壓力太大了。',
    },
  }),
  T({
    id: 'dy-pharmacy', name: '陳藥師', shopName: '仁心藥局', shopType: 'pharmacy',
    traits: ['friendly', 'shy'], skill: 3, maxRentTier: 1,
    intro: '我爸以前在這條街開藥局。他退休後藥局就關了……村裡的老人家要拿藥，得跑到很遠的地方。',
    look: look({ skin: 0xf5d0b0, hair: 0x2a1d17, hairStyle: 'short', shirt: 0xf6f6f6, pants: 0x54627a, accessory: 'glasses', age: 'mid' }),
    arrive: { minDay: 7 },
    lines: {
      hello: '血壓計放在門口，大家可以自己量。',
      happy: ['阿嬤說我跟我爸一樣細心。', '今天幫十幾個老人家量了血壓。'],
      unhappy: ['連鎖藥局比較便宜……', '是不是應該回城市上班……'],
      idle: ['感冒糖漿不要一次喝太多喔。', '我爸那時候，賣最多的是克風邪跟友露安。', '有什麼不舒服，都可以來聊聊。'],
      rival: ['……我不太會吵架。', '大家都是為了老人家好。'],
      friend: ['這個維他命送你。', '最近天氣變化大，多穿一點。'],
      refuse: '對不起，這個租金我負擔不起……',
    },
  }),
  T({
    id: 'dy-ice', name: '阿玉', shopName: '阿玉冰店', shopType: 'icepop',
    traits: ['hardworking', 'creative'], skill: 3, maxRentTier: 1,
    intro: '我平常在龍眼焙灶幫忙。阿蘭姐說，你找回了以前冰店的作法？四果冰、紅茶、冬瓜茶……我想試試看，讓冰店重新開張！',
    look: look({ skin: 0xd9a27a, hair: 0x2a1d17, hairStyle: 'bob', shirt: 0x5fa8c9, pants: 0x54627a, accessory: 'none', age: 'young' }),
    relations: { 'dy-lan': 40 },
    arrive: { flag: 'recipe-icepop' },
    lines: {
      hello: '冬瓜茶煮好了，冰店開張！',
      happy: ['阿公吃了一口說：「就是這個！」', '小朋友排成一排在等冰！'],
      unhappy: ['天氣冷，沒人吃冰……', '冬瓜茶是不是煮得不夠久？'],
      idle: ['四果要自己醃，外面買的不夠味。', '紅茶煮好要馬上冰起來，才不會苦。'],
      rival: ['我會做得比以前更好吃！', '老店也可以有新的人來顧啊。'],
      friend: ['請你吃一碗！', '加一球芋頭給你。'],
      refuse: '冰一碗才幾十塊，太貴了啦。',
    },
  }),
  T({
    id: 'dy-koe', name: '阿梅', shopName: '阿梅盤仔粿', shopType: 'platekoe',
    traits: ['hardworking', 'friendly'], skill: 3, maxRentTier: 1,
    intro: '我從印尼嫁來東原，平常在果園工作。以前常吃隔壁阿姨做的盤子碗粿……你找回作法了？我想學！',
    look: look({ skin: 0xc98e66, hair: 0x111111, hairStyle: 'bun', shirt: 0xd9a03b, pants: 0x3d3a36, accessory: 'apron', age: 'mid' }),
    relations: { 'dy-lan': 30, 'dy-ice': 25 },
    arrive: { flag: 'recipe-platekoe' },
    lines: {
      hello: '用盤子蒸，碗粿才會薄薄的、熟得快！',
      happy: ['花生糯米腸賣光了！', '阿嬤說我做得跟以前一模一樣。'],
      unhappy: ['米漿好像沒調好……', '下午都沒有人來。'],
      idle: ['為什麼用盤子？因為比較快熟啊！', '糯米腸要灌得剛剛好，不能太滿。'],
      rival: ['我很努力在學了！', '東原也是我的家。'],
      friend: ['幫你留一條糯米腸。', '一起吃早餐吧！'],
      refuse: '這個價錢，我做不起來。',
    },
  }),
  T({
    id: 'dy-mantou', name: '胖哥', shopName: '胖哥炸饅頭', shopType: 'mantou',
    traits: ['friendly', 'gossip'], skill: 3, maxRentTier: 1,
    intro: '小時候放學最期待的，就是街上那顆炸饅頭！外皮酥、裡面軟。現在沒人做了，我來做！',
    look: look({ skin: 0xe8b48f, hair: 0x2a1d17, hairStyle: 'short', shirt: 0xf2b84b, pants: 0x3d3a36, accessory: 'apron', age: 'mid' }),
    relations: { 'dy-baozi': -40 },
    arrive: { flag: 'recipe-mantou' },
    lines: {
      hello: '油鍋熱了，饅頭下鍋！',
      happy: ['炸饅頭配豆漿，賣到斷貨！', '國中生放學都衝過來！'],
      unhappy: ['油價又漲了……', '大家都說要健康，不吃炸的了。'],
      idle: ['饅頭要放一天再炸，才會酥。', '加煉乳是我的發明。'],
      rival: ['包子？那是饅頭的親戚啦！', '酥脆，才是正義！'],
      friend: ['剛炸好的，拿去！', '下次一起去十八重溪釣魚。'],
      refuse: '炸饅頭很便宜啦，這租金付不起。',
    },
  }),
  T({
    id: 'dy-smith', name: '打鐵伯', shopName: '東原打鐵舖', shopType: 'blacksmith',
    traits: ['veteran', 'stubborn'], skill: 4, maxRentTier: 1,
    intro: '打鐵舖關了十幾年了。你們年輕人，真的想學這種又熱又累的手藝？……好，那我再開一次爐。',
    look: look({ skin: 0xb07a52, hair: 0xd9d4cc, hairStyle: 'short', shirt: 0x5b5f73, pants: 0x3d3a36, accessory: 'apron', age: 'old' }),
    arrive: { flag: 'recipe-blacksmith' },
    lines: {
      hello: '爐子生火了。',
      happy: ['有個遊客訂了一把菜刀，說要傳給孫子。', '舉重隊的孩子來幫我拉風箱。'],
      unhappy: ['現在大家都用工廠的刀了。', '手沒以前有力了。'],
      idle: ['鐵要燒到橘紅色才能打。', '一把好鋤頭，可以用二十年。'],
      rival: ['做手藝的，不跟人吵。', '打出來的東西會說話。'],
      friend: ['這把小刀送你，削水果好用。', '你要不要學？'],
      refuse: '這個價錢，爐子的炭都買不起。',
    },
  }),
];

// =====================================================================
// 劇情
// =====================================================================

const stories: StoryEvent[] = [
  {
    id: 'dy-intro', street: ST, once: true, priority: 99, when: 'morning',
    cond: () => ({}),
    script: () => [
      narrate('二〇一六年，台南東山，東原。這條街以前叫「大埔街」，糖廠還在的時候，有戲院、旅社、布莊，熱鬧到半夜。'),
      narrate('現在，一半的房子都關著。'),
      focus({ landmark: 'kiln' }),
      appear('dyStudent', { landmark: 'kiln' }),
      appear('me', { landmark: 'kiln' }, -90),
      say('dyStudent', '會長，你來了！我是小穎。三年前跟著大學的計畫來東原，計畫結束了，我留了下來。'),
      say('dyStudent', '這座龍眼窯，以前是戲院。現在每到龍眼季，還是會冒煙喔。'),
      say('dyStudent', '老實說……這裡沒什麼遊客，租金也很低。在東原，錢不是最重要的。'),
      emote('me', 'idea'),
      say('dyStudent', '最重要的是「回憶」。往事、味道、人情、手藝。'),
      say('dyStudent', '空屋的屋主大多住在外地。要讓他們願意把房子租出來，得帶著他們記得的東西去說服他們。'),
      focus('dy-meatball'),
      appear('dy-meatball'),
      say('dy-meatball', '少年仔，坐。先吃一碗肉圓。'),
      say('dy-meatball', '平常街上都是村裡的人，買菜、剪頭髮、拿藥。週末才會有騎腳踏車的、坐遊覽車的來。'),
      say('dy-meatball', '村裡的人邊吃邊聊，以前的事，就會慢慢講出來。'),
      say('dyStudent', '居民在店裡聊天，就會累積回憶點數。給居民的店越多，大家越把這條街當成自己的。'),
      say('dyStudent', '來，這些是我這三年做文史採集記下來的，先給你用。'),
      effect({ memory: { past: 2, bond: 3 } }),
      narrate('得到回憶：往事 2、人情 3。點選空屋，可以找屋主談談。'),
      leave('dy-meatball'), leave('dyStudent'), leave('me'),
    ],
  },
  {
    id: 'dy-light', street: ST, once: true, priority: 60, when: 'evening',
    cond: (c) => (c.s.day >= 2 && c.has('dy-meatball') ? {} : null),
    script: () => [
      narrate('天黑了。整條街，只剩肉圓店的燈還亮著。'),
      focus('dy-meatball'),
      appear('dy-meatball'),
      appear('me', 'dy-meatball', -100),
      say('dy-meatball', '我小時候，這條街晚上比白天熱鬧。戲院散場，人潮一路湧到街尾。'),
      say('dy-meatball', '那時候我在阿爸的攤子幫忙顧，戲院一散場，肉圓一下子就賣光。'),
      emote('dy-meatball', 'music'),
      say('dy-meatball', '現在啊，我是這條街最後一盞燈。只要燈還亮著，就會有人回來吧。'),
      emote('me', 'heart'),
      effect({ memory: { past: 2, bond: 1 } }),
      narrate('得到回憶：往事 2、人情 1。'),
      leave('dy-meatball'), leave('me'),
    ],
  },
  {
    id: 'dy-weekday', street: ST, once: true, priority: 40, when: 'noon',
    cond: (c) => (c.s.day >= 2 && !isWeekend(c.s) && c.has('dy-lan') ? {} : null),
    script: () => [
      focus('dy-lan'),
      appear('dyResident', 'dy-lan', 60),
      appear('dy-lan'),
      say('dyResident', '阿蘭，給我一包鹽，還有……你婆婆以前那個四果冰，還有冬瓜茶，好久沒吃了。'),
      say('dy-lan', '阿嬤，那個我不會做啦。婆婆走得太突然，作法沒有留下來。'),
      emote('dyResident', 'sad'),
      appear('dyStudent', 'dy-lan', 170),
      say('dyStudent', '會長，有些老店的作法已經失傳了。要找回那個「味道」，冰店才能重新開張。'),
      say('dyStudent', '居民在吃東西的店聊天，會想起以前的味道；剪頭髮的時候，最愛講往事。'),
      effect({ memory: { taste: 1 } }),
      narrate('得到回憶：味道 1。湊齊回憶後，可以在右邊的「回憶」裡讓老店重新開張。'),
      leave('dyResident'), leave('dy-lan'), leave('dyStudent'),
    ],
  },
  {
    id: 'dy-film', street: ST, once: true, priority: 70, when: 'evening',
    cond: (c) => (c.s.day >= 3 ? {} : null),
    script: () => [
      focus({ landmark: 'kiln' }),
      narrate('傍晚，龍眼窯冒出淡淡的煙，空氣裡都是龍眼木的香味。'),
      appear('dyStudent', { landmark: 'kiln' }),
      appear('me', { landmark: 'kiln' }, -90),
      say('dyStudent', '你看窯上面那塊舊木頭，上面還看得到「東原戲院」幾個字。'),
      say('dyStudent', '小時候大家都看露天電影。搭一塊白布，就是電影院了。十二生肖那種冒險片，大家看到都會背台詞。'),
      emote('dyStudent', 'music'),
      say('dyStudent', '村裡有個傳說：在這座窯前面掛一塊白布，放一卷沒有人看過的老膠卷……'),
      say('dyStudent', '白布上，會出現以前的東原。'),
      emote('me', 'shock'),
      say('dyStudent', '哈哈，嚇到你了？……不過，我真的在倉庫找到一卷老膠卷，還有一台舊放映機。'),
      say('dyStudent', '標籤上寫著「東原・一九九五」。要不要……今晚就放放看？'),
      choice('白布、放映機、一卷老膠卷',
        opt('現在就放', { flag: ['film', 'tripNow'] }, [
          narrate('舉重隊的孩子幫忙在窯前搭起竹竿，掛上一塊白布。放映機喀啦喀啦地轉了起來……'),
        ]),
        opt('改天再說', { flag: ['film'] }, [
          say('dyStudent', '好，白布我先掛著。每天傍晚以後點龍眼窯，就可以放。'),
        ]),
      ),
      leave('dyStudent'), leave('me'),
    ],
  },
  {
    id: 'dy-rain', street: ST, once: true, priority: 30, when: 'noon',
    cond: (c) => (c.s.weather === 'rain' && c.has('dy-meatball') ? {} : null),
    script: () => [
      narrate('雨下得很大，街上一個人都沒有。肉圓店的燈還是亮著。'),
      focus('dy-meatball'),
      appear('dy-meatball'),
      appear('me', 'dy-meatball', -100),
      say('me', '肉圓伯，雨這麼大，今天要不要早點收？'),
      say('dy-meatball', '不行啦。說不定有人淋著雨，就是想吃一碗熱的。'),
      say('dy-meatball', '客人在等，店就要開。我阿爸教我的。'),
      appear('dyResident2', 'dy-meatball', 90),
      say('dyResident2', '（全身濕透）呼……還好有開！老闆，兩顆！'),
      emote('dy-meatball', 'music'),
      effect({ memory: { bond: 2 }, kinship: 2 }),
      narrate('得到回憶：人情 2。'),
      leave('dyResident2'), leave('dy-meatball'), leave('me'),
    ],
  },
  {
    id: 'dy-barber-gossip', street: ST, cooldown: 6, chance: 0.5, priority: 12, when: 'noon',
    cond: (c) => (c.has('dy-barber') && c.s.day >= 3 ? {} : null),
    script: (_b, c) => [
      focus('dy-barber'),
      appear('dy-barber'),
      appear('dyResident2', 'dy-barber', 80),
      say('dyResident2', '阿財，你記得以前另外兩間理髮店嗎？'),
      say('dy-barber', c.rand() < 0.5
        ? '記得啊！街頭那間的師傅，剪到一半跑去戲院看電影，客人頂著半顆頭在店裡等！'
        : '街尾那間的老闆娘最會講古。她說戲院後面那條巷子，晚上會聽到有人在唱歌仔戲……'),
      say('dyResident2', '亂講！我聽到的版本不是這樣！'),
      emote('dy-barber', 'sweat'),
      narrate('三間理髮店，三個版本。不過每一個版本裡，東原都好熱鬧。'),
      effect({ memory: { past: 1 } }),
      leave('dyResident2'), leave('dy-barber'),
    ],
  },
  {
    id: 'dy-lifters', street: ST, cooldown: 6, chance: 0.5, priority: 14, when: 'noon',
    cond: (c) => (c.has('dy-lan') && c.s.day >= 3 ? {} : null),
    script: () => [
      focus('dy-lan'),
      appear('dy-lan'),
      say('dy-lan', '唉喲，這兩包米好重……'),
      appear('dyLifter', 'dy-lan', 90),
      appear('dyLifter2', 'dy-lan', 140),
      say('dyLifter', '阿姨，我們來！'),
      say('dyLifter2', '我們是東原國中舉重隊的！這個很輕啦！'),
      fx('sparkle', 'dyLifter'),
      emote('dy-lan', 'heart'),
      say('dy-lan', '東原國中的舉重隊很厲害喔，學長還去比過奧運！'),
      effect({ memory: { bond: 1 }, kinship: 2 }),
      leave('dyLifter'), leave('dyLifter2'), leave('dy-lan'),
    ],
  },
  {
    id: 'dy-smith-visit', street: ST, cooldown: 5, chance: 0.6, priority: 13, when: 'noon',
    cond: (c) => (c.s.day >= 5 && c.s.kinship >= 40 && !c.has('dy-smith') && !c.s.recipes.includes('blacksmith') ? {} : null),
    script: () => [
      focus('dy-barber'),
      appear('dySmith', 'dy-barber', 70),
      appear('dy-barber'),
      say('dy-barber', '打鐵伯，我的剪刀又鈍了，幫我看一下。'),
      say('dySmith', '拿來。……你看，刀口要這樣斜斜地磨，一下一下，不能急。'),
      appear('me', 'dy-barber', -100),
      emote('me', 'idea'),
      say('dySmith', '以前我的打鐵舖，整天叮叮噹噹。鋤頭、鐮刀、菜刀，全村都是我打的。'),
      say('dySmith', '現在？爐子冷了十幾年囉。舖子後來租給人家賣包子，打鐵的聲音變成蒸籠的煙。'),
      effect({ memory: { craft: 2 } }),
      narrate('得到回憶：手藝 2。學會足夠的手藝，打鐵伯也許願意再開一次爐。'),
      leave('dySmith'), leave('dy-barber'), leave('me'),
    ],
  },
  {
    id: 'dy-cyclists', street: ST, cooldown: 7, chance: 0.7, priority: 20, when: 'morning',
    cond: (c) => (isWeekend(c.s) ? {} : null),
    script: () => [
      narrate('週末早上，一隊單車騎進了東原。'),
      focus('dy-meatball'),
      appear('cyclist', 'dy-meatball', 80),
      say('cyclist', '各位！這裡就是傳說中全年無休的肉圓！補給站到了！'),
      appear('dy-meatball'),
      say('dy-meatball', '好好好，慢慢來，一人兩顆。'),
      emote('cyclist', 'star'),
      choice('單車隊問附近還有什麼好玩的',
        opt('推薦龍眼窯和老屋，拍照很好看', { rep: 2 }, [say('cyclist', '老屋配龍眼窯，這個景我喜歡！')]),
        opt('推薦居民常去的小吃，吃在地的', { kinship: 2, rep: 1 }, [say('cyclist', '在地人吃的，一定好吃！'), emote('dy-meatball', 'music')]),
      ),
      leave('cyclist'), leave('dy-meatball'),
    ],
  },
  {
    id: 'dy-bus', street: ST, cooldown: 7, chance: 0.6, priority: 18, when: 'noon',
    cond: (c) => (isWeekend(c.s) && c.s.day >= 6 ? {} : null),
    script: () => [
      narrate('一台遊覽車停在村口，一群遊客跟著小旗子走進老街。'),
      focus({ landmark: 'kiln' }),
      appear('busGuide', { landmark: 'kiln' }),
      appear('tourist', { landmark: 'kiln' }, 90),
      say('busGuide', '各位，這裡是東原！我們停留四十分鐘喔！'),
      say('tourist', '這裡……有什麼可以買的嗎？好安靜喔。'),
      appear('me', { landmark: 'kiln' }, -100),
      choice('遊客想找地方逛',
        opt('帶大家去看戲院原址，講糖廠時代的故事', { rep: 2, memory: { past: 1 } }, [
          say('tourist', '原來這裡以前有戲院！好想看看以前的樣子。'),
          emote('tourist', 'star'),
        ]),
        opt('請大家照顧老店：買肉圓、買龍眼乾', { buff: { id: 'dy-bus', name: '遊覽車客人', days: 1, mods: { traffic: 1.25 } } }, [
          say('busGuide', '好，大家先去吃肉圓，十五分鐘後集合！'),
        ]),
      ),
      leave('busGuide'), leave('tourist'), leave('me'),
    ],
  },
  {
    id: 'dy-kinship-low', street: ST, cooldown: 6, priority: 45, when: 'morning',
    cond: (c) => (c.s.kinship < 30 ? {} : null),
    script: () => [
      focus('dy-meatball'),
      appear('dyResident', 'dy-meatball', 70),
      appear('dyResident2', 'dy-meatball', 140),
      say('dyResident', '會長，最近開的店，都是給外地人的。咖啡一杯一百多塊，阮哪喝得起。'),
      say('dyResident2', '老街變得不像我們的了。'),
      emote('dyResident2', 'sad'),
      appear('me', 'dy-meatball', -100),
      choice('居民覺得老街不是自己的了',
        opt('辦一場里民茶會，聽大家說', { kinship: 10, memory: { bond: 1 } }, [
          narrate('阿嬤們帶著自己泡的茶和自己做的粿來，聊到太陽下山。'),
          emote('dyResident', 'heart'),
        ], 2000),
        opt('之後多招一些給居民的店', { kinship: 3 }, [say('dyResident', '好，阮等你喔。')]),
        opt('解釋：沒有遊客，老街活不下去', { kinship: -2, rep: 1 }, [say('dyResident2', '……也是啦。')]),
      ),
      leave('dyResident'), leave('dyResident2'), leave('me'),
    ],
  },
  {
    id: 'dy-kinship-high', street: ST, once: true, priority: 40, when: 'morning',
    cond: (c) => (c.s.kinship >= 75 ? {} : null),
    script: () => [
      focus('dy-meatball'),
      appear('dyResident', 'dy-meatball', 70),
      appear('dyResident2', 'dy-meatball', 140),
      appear('me', 'dy-meatball', -100),
      say('dyResident', '會長，這條街最近很有人情味。阮翻了老相簿，這些照片給你。'),
      say('dyResident2', '你看，這是糖廠發薪日，街上擠到走不動。這是我，站在戲院門口。'),
      emote('me', 'heart'),
      effect({ memory: { past: 4, bond: 2 } }),
      narrate('得到回憶：往事 4、人情 2。'),
      leave('dyResident'), leave('dyResident2'), leave('me'),
    ],
  },
  {
    id: 'dy-brothers', street: ST, once: true, priority: 50, when: 'noon',
    cond: (c) => (c.s.lots[5]?.unlocked && !c.s.lots[6]?.unlocked ? {} : null),
    script: () => [
      focus({ lot: 6 }),
      narrate('隔壁那間空屋前，三個男人吵了起來。'),
      appear('dyBro1', { lot: 6 }, -60),
      appear('dyBro2', { lot: 6 }, 10),
      appear('dyBro3', { lot: 6 }, 80),
      say('dyBro1', '這間是阿爸留給長子的，我說了算！'),
      say('dyBro2', '阿爸生病的時候，是誰在照顧？是我！'),
      say('dyBro3', '你們吵你們的，我只想把它賣掉。'),
      emote('dyBro1', 'anger'), emote('dyBro2', 'anger'),
      appear('me', { lot: 6 }, -150),
      choice('三兄弟吵得不可開交',
        opt('請肉圓伯出面：他看著三兄弟長大的', { flag: ['brothers-ok'], memory: { bond: 1 } }, [
          narrate('肉圓伯端著三碗肉圓走過來，一人一碗。'),
          say('dyBro1', '……阿伯，你還記得我們小時候，三個人搶一碗肉圓？'),
          say('dyBro3', '最後都是大哥讓我們吃。'),
          emote('dyBro1', 'sad'),
          say('dyBro2', '好啦，房子先租出去，租金三個人平分。'),
        ]),
        opt('請他們吃一桌，慢慢談', { flag: ['brothers-ok'] }, [
          narrate('吃到一半，三兄弟開始聊起小時候在十八重溪抓蝦的事。'),
          say('dyBro2', '……好啦，先租出去。'),
        ], 1500),
      ),
      narrate('三兄弟願意談了。準備好回憶，就可以去說服他們。'),
      leave('dyBro1'), leave('dyBro2'), leave('dyBro3'), leave('me'),
    ],
  },
  {
    id: 'dy-granddaughter', street: ST, once: true, priority: 50, when: 'evening',
    cond: (c) => (c.s.lots[6]?.unlocked && !c.s.lots[7]?.unlocked && (c.s.memories.past >= 3 || c.flag('photo-amy')) ? {} : null),
    script: (_b, c) => [
      focus({ lot: 7 }),
      appear('dyStudent', { lot: 7 }),
      appear('me', { lot: 7 }, -90),
      say('dyStudent', '這間的屋主是一位在國外工作的孫女。我寫信給她好幾次，她都說「那裡已經沒有我認識的人了」。'),
      ...(c.flag('photo-amy')
        ? [say('me', '……我有一張照片。'), narrate('不知道為什麼，你的口袋裡，有一張一九九五年拍的照片。')]
        : [say('dyStudent', '可是……我在老相簿裡，找到這張照片。')]),
      narrate('照片裡，一個綁辮子的小女孩，站在這間房子門口，手裡拿著一支冰棒。'),
      say('dyStudent', '我傳給她了。'),
      narrate('過了很久，手機亮了起來。'),
      narrate('「那是我。阿公每天都買冰棒給我。……我想再聽聽老家的事。」'),
      emote('dyStudent', 'heart'),
      effect({ flag: ['granddaughter'] }),
      leave('dyStudent'), leave('me'),
    ],
  },
  {
    id: 'dy-rivals', street: ST, cooldown: 8, chance: 0.6, priority: 22, when: 'noon',
    cond: (c) => (c.has('dy-baozi') && c.has('dy-mantou') ? {} : null),
    script: () => [
      focus('dy-baozi'),
      appear('dy-baozi'),
      appear('dy-mantou', 'dy-baozi', 120),
      say('dy-baozi', '包子有餡，饅頭沒有。這還用比嗎？'),
      say('dy-mantou', '炸過的饅頭外酥內軟，包子會嗎？'),
      emote('dy-baozi', 'anger'), emote('dy-mantou', 'anger'),
      appear('dyLifter', 'dy-baozi', 220),
      say('dyLifter', '……我兩個都要。'),
      choice('包子對炸饅頭',
        opt('辦一場「早餐對決」，讓居民投票', { sat: [['dy-baozi', 5], ['dy-mantou', 5]], kinship: 2, rel: [['dy-baozi', 'dy-mantou', 10]] }, [
          narrate('結果：平手。居民說兩個都要吃，才是東原的早餐。'),
          emote('dy-baozi', 'sweat'),
        ]),
        opt('建議推「包子加炸饅頭」套餐', { rel: [['dy-baozi', 'dy-mantou', 20]], rep: 1 }, [
          say('dy-mantou', '……好像不錯。'),
          say('dy-baozi', '哼，只是剛好而已。'),
        ]),
      ),
      leave('dy-baozi'), leave('dy-mantou'), leave('dyLifter'),
    ],
  },
  {
    id: 'dy-recipe-open', street: ST, cooldown: 1, priority: 55, when: 'morning',
    cond: (c) => {
      const r = c.s.recipes.find((x) => !c.s.flags.includes(`recipe-told-${x}`));
      return r ? { r } : null;
    },
    script: (b) => {
      const who = { icepop: 'dy-ice', platekoe: 'dy-koe', mantou: 'dy-mantou', blacksmith: 'dy-smith' }[b.r] ?? '';
      return [
        narrate({
          icepop: '自己醃的四果鋪在剉冰上，大鍋紅茶、冬瓜茶冰得涼涼的——冰店的作法，找回來了。',
          platekoe: '米漿倒進盤子，蒸到邊緣微微捲起——盤子碗粿的作法，找回來了。',
          mantou: '饅頭放一天，下鍋炸到金黃——炸饅頭的作法，找回來了。',
          blacksmith: '鐵燒到橘紅，一下一下地打——打鐵的手藝，傳下來了。',
        }[b.r] ?? '老店的作法找回來了。'),
        effect({ flag: [`recipe-told-${b.r}`], applicant: who ? [who] : [] }),
        narrate('有人來佈告欄應徵，想讓這間老店重新開張。'),
      ];
    },
  },
  {
    id: 'dy-smith-remember', street: ST, once: true, priority: 48, when: 'morning',
    cond: (c) => (c.flag('p95-blacksmith') && !c.has('dy-smith') && c.has('dy-barber') ? {} : null),
    script: () => [
      focus('dy-barber'),
      appear('dySmith', 'dy-barber', 70),
      appear('me', 'dy-barber', -100),
      say('dySmith', '……少年仔，你過來一下。'),
      say('dySmith', '你怎麼跟我年輕時候，那個來幫我拉風箱的少年仔，長得一模一樣？'),
      emote('me', 'sweat'),
      say('dySmith', '那個少年仔手很穩。我還跟他說，以後想學就來找我。……他後來再也沒來過。'),
      say('dySmith', '你要是想學，我就再開一次爐。'),
      ...[effect({ memory: { craft: 2 } }), narrate('得到回憶：手藝 2。打鐵伯願意教了，打鐵舖需要的回憶也變少了。')],
      leave('dySmith'), leave('me'),
    ],
  },
  {
    id: 'dy-ice-remember', street: ST, once: true, priority: 47, when: 'morning',
    cond: (c) => (c.flag('p95-icepop') && c.has('dy-lan') ? {} : null),
    script: () => [
      focus('dy-lan'),
      appear('dy-lan'),
      appear('me', 'dy-lan', -100),
      say('dy-lan', '會長，我昨天晚上夢到婆婆。'),
      say('dy-lan', '她以前常說，很久以前有個年輕人來冰店幫忙煮冬瓜茶、醃四果，做得很認真。她說：「媳婦要是肯學，我就教她。」'),
      say('dy-lan', '……可是我嫁過來的時候，冰店已經收了。'),
      emote('dy-lan', 'sad'),
      say('me', '那個作法，我記得。'),
      emote('dy-lan', 'shock'),
      effect({ memory: { bond: 2 }, kinship: 2 }),
      narrate('得到回憶：人情 2。'),
      leave('dy-lan'), leave('me'),
    ],
  },
  {
    id: 'dy-meatball-1960', street: ST, once: true, priority: 46, when: 'evening',
    cond: (c) => (c.flag('p60-meatball') && c.has('dy-meatball') ? {} : null),
    script: () => [
      focus('dy-meatball'),
      appear('dy-meatball'),
      appear('me', 'dy-meatball', -100),
      say('dy-meatball', '少年仔，我跟你說一件很奇怪的事。'),
      say('dy-meatball', '我十歲那年，在阿爸的攤子顧店。有一個不認識的年輕人來幫忙，還問我幾歲。'),
      say('dy-meatball', '我跟他說，我以後要賣肉圓，一年三百六十五天都開。'),
      say('dy-meatball', '……那個人，長得跟你一模一樣。'),
      emote('me', 'sweat'),
      say('dy-meatball', '哈哈，老了，記性不好。來，吃一顆。我說到做到了吧？'),
      emote('dy-meatball', 'heart'),
      effect({ memory: { bond: 2 }, kinship: 2 }),
      narrate('得到回憶：人情 2。'),
      leave('dy-meatball'), leave('me'),
    ],
  },
  {
    id: 'dy-forge-baozi', street: ST, once: true, priority: 49, when: 'morning',
    cond: (c) => (c.s.lots[9]?.shop?.tenantId === 'dy-baozi' ? {} : null),
    script: () => [
      focus({ lot: 9 }),
      appear('dy-baozi', { lot: 9 }),
      appear('dySmith', { lot: 9 }, 90),
      appear('me', { lot: 9 }, -100),
      narrate('一大早，打鐵伯拄著拐杖，站在自己的舊舖子門口。蒸籠冒出白白的煙。'),
      say('dySmith', '……秀枝，你的蒸籠擺的那個位置，就是我以前的爐子。'),
      say('dy-baozi', '打鐵伯！我阿母以前也是在這裡蒸包子。她常說，冬天靠著那面牆，還感覺得到爐子的溫度。'),
      say('dySmith', '哈哈哈。打鐵的聲音沒了，換成包子的香味，也不錯。來，給我兩顆，高麗菜的。'),
      emote('dySmith', 'heart'),
      effect({ memory: { bond: 2, past: 1 }, kinship: 3, sat: [['dy-baozi', 10]] }),
      narrate('得到回憶：人情 2、往事 1。'),
      leave('dySmith'), leave('dy-baozi'), leave('me'),
    ],
  },
  {
    id: 'dy-pilgrim-map', street: ST, once: true, priority: 52, when: 'morning',
    cond: (c) => (c.s.trips >= 1 ? {} : null),
    script: () => [
      focus({ landmark: 'kiln' }),
      appear('dyStudent', { landmark: 'kiln' }),
      appear('me', { landmark: 'kiln' }, -90),
      say('dyStudent', '會長，我做了一張「回憶巡禮地圖」。戲院原址、冰店、碗粿店、打鐵舖、老榕樹……'),
      say('dyStudent', '每個地方，都藏著一段以前的故事。你在白布電影裡找回的回憶，帶回來這裡，就可以把那個地方「點亮」。'),
      say('dyStudent', '房子還關著的地方，要先說服屋主才行。全部點亮的那天……我們來辦一場真正的白布電影之夜吧。'),
      emote('me', 'star'),
      narrate('右邊的「巡禮」可以看到所有巡禮點。點亮全部巡禮點就能過關。'),
      leave('dyStudent'), leave('me'),
    ],
  },
  {
    id: 'dy-ending', street: ST, once: true, priority: 99, when: 'evening',
    cond: (c) => (c.street.goals.every((g) => g.check(c.s)) ? {} : null),
    script: () => endingSteps(),
  },
];

// =====================================================================
// 老街
// =====================================================================

export const DONGYUAN: StreetDef = {
  id: ST,
  name: '東原老街',
  region: '台南市東山區',
  difficulty: 5,
  tagline: '時空跳躍・回憶點數',
  intro: '舊稱「大埔街」，糖廠興盛的年代有戲院、旅社、布莊，熱鬧到半夜。糖廠收了以後人潮散去，現在一半的房子都關著。在這裡，錢不是最重要的——要找回散落的回憶，才能讓屋主回來、讓老店重新開張。',
  map: { x: 0.465, y: 0.695 },
  playable: true,
  facade: 'oldtown',
  backdrop: 'orchard',
  ground: 'brick',
  layout: [
    { kind: 'landmark', id: 'treehouse' },
    { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' },
    { kind: 'landmark', id: 'clinic' },
    { kind: 'landmark', id: 'kiln' },
    { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' },
    { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' },
  ],
  landmarks: [
    { id: 'treehouse', name: '老榕樹樹屋', description: '大學生團隊和村民一起在老榕樹上搭的樹屋。夏天傍晚，國中生會爬上去寫功課。', width: 300 },
    { id: 'clinic', name: '街角小診所', description: '老街上的小診所，已經很久沒開門了。玻璃門上的紅十字褪成了粉紅色。', width: 200 },
    { id: 'kiln', name: '戲院原址・龍眼窯', description: '這裡曾經是東原戲院。荒廢多年後，改建成烘焙龍眼乾的窯。窯上還留著一塊寫著「東原戲院」的舊木頭。', width: 320 },
  ],
  startLots: 4,
  startMoney: 25000,
  startRep: 5,
  baseTraffic: 6,
  repTraffic: 0.35,
  weekendMult: 1.8,
  rentMult: 0.6,
  maintenance: 300,
  lotCost: 0,
  weather: { rain: 0.2, fog: 0.05 },
  visitors: { jp: 0, kr: 0 },
  closeHour: 21.5,
  memory: {
    residents: 13,
    startTenants: [
      { lot: 0, tenant: 'dy-meatball', tier: 0 },
      { lot: 1, tenant: 'dy-lan', tier: 0 },
      { lot: 2, tenant: 'dy-barber', tier: 0 },
    ],
    startMemories: {},
    past1995: PAST_1995,
    past1960: PAST_1960,
    pilgrimage: PILGRIMAGE,
    pilgrimStory: pilgrimSteps,
    tripIntro: (s, era) => (era === 1960 ? tripIntro1960(s) : tripIntro(s, era)),
    tripOutro,
    pastLandmark: (s, era, id) => (era === 1960 ? pastLandmark1960(s, id) : pastLandmark(s, era, id)),
    owners: [
      {
        name: '台北工程師 阿凱', tag: '屋主：台北工程師',
        pitch: '老家喔？我一年回來一次而已。租金合理、有人顧，就租吧。……不過，你可以跟我說說，我阿嬤以前在這裡賣什麼嗎？',
        thanks: '原來阿嬤以前在這裡賣菜頭粿……好，房子交給你。過年我會回來看看。',
        cost: { bond: 2 }, money: 3000,
      },
      {
        name: '顧神明廳的金鳳嬤', tag: '屋主：金鳳嬤',
        pitch: '二樓是阮的神明廳，每天要上香。房子要租，可以，但阮要看是什麼人。',
        thanks: '你是有心的人。神明廳的香，就拜託租客幫忙點了。',
        cost: { bond: 4, past: 1 }, money: 2000, rule: 'trusted',
      },
      {
        name: '分家吵不停的三兄弟', tag: '屋主：三兄弟',
        pitch: '（三兄弟各說各話，誰也不讓誰。）',
        thanks: '三兄弟難得坐在一起吃了頓飯。「房子租出去，租金三個人平分。」',
        cost: { bond: 3, past: 2 }, money: 4000,
        needFlag: 'brothers-ok', needText: '三兄弟還在吵架，先等他們願意坐下來談。',
      },
      {
        name: '在國外工作的孫女 Amy', tag: '屋主：國外的孫女',
        pitch: '「那裡已經沒有我認識的人了。」……可是，如果你能跟我說說阿公以前的事……',
        thanks: '「阿公種的那盆九重葛，還開著花嗎？房子租給你，只要幫我澆澆花就好。」',
        cost: { past: 4, bond: 2 }, money: 2000, rule: 'flowers',
        needFlag: 'granddaughter', needText: '她還沒想起老家。也許一張以前的照片，能讓她想起來。',
      },
      {
        name: '回鄉的退休老師', tag: '屋主：退休老師',
        pitch: '我在東原國小教了三十年書。退休了想回來，但房子是阿爸蓋的，一磚一瓦都不能動。',
        thanks: '好，就照原樣租給你。哪天有空，來聽我講以前糖廠的事。',
        cost: { past: 4, taste: 2, bond: 3 }, money: 5000, rule: 'noRenovate',
      },
      {
        name: '打鐵伯（以前的打鐵舖）', tag: '屋主：打鐵伯',
        pitch: '這間是我以前的打鐵舖。爐子熄了以後，租給隔壁包子嬸賣包子，一賣二十年。後來她老了，舖子就空著……要租，你先陪我講講以前打鐵的事。',
        thanks: '好，鑰匙拿去。最好還是租給賣包子的。這間舖子啊，沒有蒸籠的煙，我不習慣。',
        cost: { past: 3, bond: 3 }, money: 4000,
      },
      {
        name: '大鼓隊教練', tag: '屋主：大鼓隊教練',
        pitch: '房子是我爸留下的，我想租給能讓孩子們有地方去的人。你懂這條街嗎？',
        thanks: '孩子們放學可以來這裡練鼓了。謝謝你。',
        cost: { past: 5, bond: 4, craft: 1 }, money: 6000,
      },
    ],
    recipes: [
      { shop: 'icepop', name: '冰店（四果冰、紅茶、冬瓜茶）', cost: { taste: 5, past: 1 }, discount: { taste: 3 }, text: '阿蘭的婆婆以前開的。在 1995 年的冰店學過的話，需要的回憶會變少。' },
      { shop: 'mantou', name: '炸饅頭', cost: { taste: 4, bond: 1 }, discount: { taste: 2 }, text: '放學的國中生最愛。在 1995 年的饅頭店學過的話，需要的回憶會變少。' },
      { shop: 'platekoe', name: '盤子碗粿＋花生糯米腸', cost: { taste: 7, bond: 2 }, discount: { taste: 4 }, text: '用盤子蒸，碗粿薄薄的、熟得快。在 1995 年學過的話，需要的回憶會變少。' },
      { shop: 'blacksmith', name: '打鐵舖', cost: { craft: 5, past: 1 }, discount: { craft: 2 }, text: '打鐵伯的手藝。在 1995 年幫他拉過風箱的話，需要的回憶會變少。' },
    ],
  },
  shopTypes: ['meatball', 'grocery', 'barber', 'pharmacy', 'baozi', 'ribsoup', 'longan', 'cafe', 'icepop', 'platekoe', 'mantou', 'blacksmith'],
  tenants,
  stories,
  activities: {
    templeFair: { name: '大鼓舞龍踩街', temple: '東原國中' },
    mascots: [
      { id: 'longan', name: '龍眼仔', description: '焙灶裡跑出來的龍眼，殼裂開露出晶亮的果肉。吃的店 +12%。', mods: { appeal: { food: 1.12 } } },
      { id: 'sugar', name: '黑糖膏', description: '一杯會走路的黑糖膏，走過的地方甜甜的。居民和遊客都喜歡，人潮 +8%。', mods: { traffic: 1.08 } },
      { id: 'tricycle', name: '三輪車阿伯', description: '騎著載滿甘蔗的農用三輪車，慢慢地繞老街。日常類 +15%。', mods: { appeal: { daily: 1.15 } } },
    ],
    legends: [
      { id: 'film', name: '白布上的老東原', description: '「在龍眼窯前看露天電影，會看到以前的東原。」很浪漫，有點難證明。', risk: 0.25, mods: { traffic: 1.15 } },
      { id: 'meatball', name: '全年無休的肉圓', description: '「颱風天也開的肉圓，吃了會有好運。」溫和可信，幾乎不會出事。', risk: 0.05, mods: { appeal: { food: 1.12 } } },
    ],
  },
  goals: [
    { id: 'pilgrimage', text: `點亮所有回憶巡禮點（${PILGRIMAGE.length} 個）`, check: (s) => pilgrimageDone(s) },
    { id: 'kinship', text: '鄉親認同達到 100', check: (s) => s.flags.includes('kinship100') },
  ],
};
