import type { StreetDef, TenantProfile, StoryEvent, GameState } from '../core/types';
import { springRatio, springRecovered, isSpringShop } from '../core/onsen';
import { say, emote, narrate, focus, appear, leave, fx, effect, choice, opt, look } from './dsl';
import { GUANZILING_EVENTS } from './guanzilingEvents';
import { GUANZILING_FEST } from './guanzilingFest';

const ST = 'guanziling';
const shops = (s: GameState) => s.lots.filter((l) => l.shop).length;

const T = (t: Omit<TenantProfile, 'street'>): TenantProfile => ({ ...t, street: ST });

const tenants: TenantProfile[] = [
  T({
    id: 'gz-ryokan', name: '秀子姨', shopName: '嶺泉館', shopType: 'ryokan',
    traits: ['veteran', 'stubborn'], skill: 5, maxRentTier: 2,
    intro: '阮這間嶺泉館，是阿祖那代從日本人手頭接過來的。泥湯要慢慢泡，人生也是。',
    look: look({ skin: 0xf2c9a5, hair: 0x5a5a5a, hairStyle: 'bun', shirt: 0x4a3a5a, pants: 0x4a3a5a, accessory: 'yukata', age: 'old' }),
    relations: { 'gz-ceo': -50, 'gz-mountain': 30 },
    lines: {
      hello: '請多指教。……おねがいします。',
      happy: ['今天的泉水，跟阿母那時陣一樣燒。', '客人說睡得很好，這樣就好。'],
      unhappy: ['水這麼溫，叫人家怎麼泡……', '一百年的招牌，不能倒在我手上。'],
      idle: ['泥湯泡完要冲乾淨喔。', '浴衣的帶子要綁在後面。'],
      rival: ['精品？泥湯哪有分精不精品。', '年輕人，錢不是什麼都買得到。'],
      friend: ['來，留下來吃飯。', '你這個囡仔，有心。'],
      refuse: '這個價錢，阮阿祖會從厝頂跳下來。',
    },
  }),
  T({
    id: 'gz-ceo', name: 'Jason 林', shopName: '泥月 Mud&Moon', shopType: 'bathhouse',
    traits: ['online', 'dramatic'], skill: 4, maxRentTier: 2,
    intro: '我在台北做了十年新創，現在要用 data 讓關子嶺 re-brand。你知道「泥漿」的 SEO 有多強嗎？',
    look: look({ skin: 0xf5d0b0, hair: 0x2a1d17, hairStyle: 'short', shirt: 0x2b2b2b, pants: 0x54627a, accessory: 'glasses', age: 'young' }),
    relations: { 'gz-ryokan': -50, 'gz-yukata': 25 },
    arrive: { minDay: 3 },
    lines: {
      hello: 'Let\'s go！一起把關子嶺做成國際品牌！',
      happy: ['今天的 conversion rate 超漂亮！', '限動被分享了三百次！'],
      unhappy: ['這個 KPI……我要重新思考人生。', '台北的同事都在笑我……'],
      idle: ['泥漿湯，是一種 lifestyle。', '我們的湯屋有香氛跟 lo-fi 音樂。'],
      rival: ['阿姨，時代變了。', '我出三倍價錢買你的招牌。'],
      friend: ['我們來 collab 吧！', '你就是我的 co-founder。'],
      refuse: '這個租金 ROI 不行啦。',
    },
  }),
  T({
    // 只會透過劇情出現：Jason 收購嶺泉館後開的精品溫泉旅館
    id: 'gz-villa', name: 'Jason（泥月 Villa）', shopName: '泥月 Villa', shopType: 'ryokan',
    traits: ['online', 'dramatic'], skill: 5, maxRentTier: 2,
    intro: '嶺泉館的木頭、屋瓦我全部留著，只是換上設計師家具和香氛。這叫 heritage luxury。',
    look: look({ skin: 0xf5d0b0, hair: 0x2a1d17, hairStyle: 'short', shirt: 0x2b2b2b, pants: 0x54627a, accessory: 'glasses', age: 'young' }),
    arrive: { flag: 'never' },
    lines: {
      hello: '泥月 Villa，soft opening！',
      happy: ['今天的房間全部 sold out！', '有部落客說這是全台南最美的溫泉旅館！'],
      unhappy: ['這個入住率……我要跟投資人怎麼交代……', '是不是不該拆掉嶺泉館的招牌……'],
      idle: ['房間的泥湯是 private 的喔。', '早餐是秀子姨教我的古早味。'],
      rival: ['我們的 target 客群不一樣。', '你應該來我們這裡 benchmark 一下。'],
      friend: ['一起做套裝行程吧！', '你就是我的 strategic partner。'],
      refuse: '這個租金 ROI 不行啦。',
    },
  }),
  T({
    id: 'gz-chicken', name: '甕伯', shopName: '甕仔雞', shopType: 'claypot',
    traits: ['veteran', 'hothead'], skill: 5, maxRentTier: 1,
    intro: '甕缸雞？我烤四十年了！關子嶺第一甕就是我起的火！……什麼？你問誰是元祖？當然是我！',
    look: look({ skin: 0xc98e66, hair: 0xd9d4cc, hairStyle: 'short', shirt: 0xf0f0f0, pants: 0x3d3a36, accessory: 'apron', age: 'old' }),
    relations: { 'gz-chicken2': -45 },
    lines: {
      hello: '好！明天開始起火！',
      happy: ['號碼牌又發完了！', '今天的雞，皮脆到會唱歌！'],
      unhappy: ['火都不旺了……', '雞烤得再好，沒人吃有什麼用。'],
      idle: ['甕要用龍眼木燒才香。', '一隻雞要烤一個多小時，急不來。'],
      rival: ['元祖是我！你還在包尿布的時候我就在烤雞了！', '你那是烤箱雞啦！'],
      friend: ['來，雞腿給你。', '一起喝一杯！'],
      refuse: '這個價錢，我的雞都要飛走了。',
    },
  }),
  T({
    id: 'gz-chicken2', name: '阿窯', shopName: '元祖窯烤雞', shopType: 'claypot',
    traits: ['online', 'hardworking'], skill: 3, maxRentTier: 1,
    intro: '我是返鄉的第三代！我阿公才是真正的元祖，只是他當年沒去登記商標……這次我要討回來！',
    look: look({ skin: 0xf2c9a5, hair: 0x4a3324, hairStyle: 'spiky', shirt: 0xb3262e, pants: 0x2f3550, accessory: 'cap', age: 'young' }),
    relations: { 'gz-chicken': -45 },
    arrive: { minDay: 3 },
    lines: {
      hello: '元祖窯烤雞，正式開幕！記得打卡！',
      happy: ['開箱影片破十萬了！', '今天外送單爆了！'],
      unhappy: ['阿公……我是不是讓你丟臉了。', '雞都烤焦了……'],
      idle: ['我們有甕缸雞便當，網路下單喔。', '要不要加購雞湯？'],
      rival: ['我阿公說你以前是幫他顧火的！', '元祖兩個字是有商標的好嗎！'],
      friend: ['幫我拍一張！', '這隻算你友情價！'],
      refuse: '這樣我會變成「元祖倒店雞」……',
    },
  }),
  T({
    id: 'gz-yukata', name: '小葵', shopName: '葵の浴衣', shopType: 'yukata',
    traits: ['creative', 'friendly'], skill: 3, maxRentTier: 1,
    intro: '我是 cosplay 社的！關子嶺有日式老街、有溫泉、還有妖怪傳說，根本就是我的夢幻場景！',
    look: look({ skin: 0xf9dcc4, hair: 0x2a1d17, hairStyle: 'ponytail', shirt: 0xef8fb1, pants: 0xef8fb1, accessory: 'yukata', age: 'young' }),
    relations: { 'gz-ceo': 25 },
    arrive: { minDay: 3 },
    lines: {
      hello: '歡迎光臨～今天想當哪個時代的人呢？',
      happy: ['好多人穿我的浴衣去好漢坡拍照！', '今天的客人都好上鏡！'],
      unhappy: ['浴衣……都沒人穿……', '我是不是該回去上班了……'],
      idle: ['這件是牽牛花圖案的喔！', '帶子要不要幫你綁蝴蝶結？'],
      rival: ['哼，品味不同不相為謀。', '我的浴衣才不是戲服！'],
      friend: ['一起拍一張！', '幫你挑一件最適合的！'],
      refuse: '這樣我連布料錢都付不起……',
    },
  }),
  T({
    id: 'gz-mountain', name: '山產阿嬤', shopName: '阿嬤山產', shopType: 'sanchan',
    traits: ['friendly', 'veteran'], skill: 4, maxRentTier: 0,
    intro: '阿嬤的野菜都是後山自己採的，香菇雞湯燉一整晚。年輕人，有空來呷一碗。',
    look: look({ skin: 0xd9a07a, hair: 0xd9d4cc, hairStyle: 'bun', shirt: 0x6a8a4a, pants: 0x3d3a36, accessory: 'apron', age: 'old' }),
    relations: { 'gz-ryokan': 30 },
    lines: {
      hello: '好好好，阿嬤明天一早就去採菜。',
      happy: ['湯都賣完了，明天要燉兩鍋！', '大家吃得好飽，阿嬤就歡喜。'],
      unhappy: ['菜都放到黃了……', '阿嬤是不是老了……'],
      idle: ['這是過貓，很脆喔。', '香菇是山上種的，很香。'],
      rival: ['阿嬤不跟你計較。', '吃飯皇帝大，不要吵。'],
      friend: ['來，這碗湯阿嬤請。', '你瘦了，多吃一點。'],
      refuse: '阿嬤賣菜的，付不起啦。',
    },
  }),
  T({
    id: 'gz-egg', name: '蛋哥', shopName: '半熟蛋哥', shopType: 'onsenegg',
    traits: ['lazy', 'gossip'], skill: 2, maxRentTier: 0,
    intro: '溫泉蛋嘛，蛋丟進去、等，撈起來。很簡單啦。剩下的時間我可以聊天。對了，你知道隔壁那間……',
    look: look({ skin: 0xe8b48f, hair: 0x2a1d17, hairStyle: 'short', shirt: 0xf2c14e, pants: 0x54627a, accessory: 'cap', age: 'mid' }),
    lines: {
      hello: '好喔，那我先去躺一下。',
      happy: ['蛋賣光了，可以休息了！', '今天聽到三個大八卦！'],
      unhappy: ['蛋都煮過頭了……', '沒人聊天好無聊……'],
      idle: ['半熟的最好吃，蛋黃會流下來。', '欸，你有聽說嗎？'],
      rival: ['我不想吵，我想睡覺。', '你的事我都知道喔。'],
      friend: ['跟你講一個秘密……', '這顆雙黃的給你。'],
      refuse: '太貴了啦，一顆蛋才賣二十。',
    },
  }),
  T({
    id: 'gz-mud', name: '灰姑娘', shopName: '灰姑娘泥漿館', shopType: 'mudspa',
    traits: ['dramatic', 'creative'], skill: 3, maxRentTier: 1,
    intro: '我就是泥漿美容教主——灰姑娘！敷上關子嶺的泥，十二點以前，你就是全場最美的人！',
    look: look({ skin: 0xb8b0a4, hair: 0x7a4a9a, hairStyle: 'long', shirt: 0xf3d6dc, pants: 0x5a5a62, accessory: 'none', age: 'young' }),
    arrive: { minDay: 3 },
    lines: {
      hello: '美麗，從一層泥開始！',
      happy: ['今天有十個人變美了！', '我的臉，今天也很灰很美！'],
      unhappy: ['我的玻璃鞋……碎了……', '泥漿都乾掉了，就像我的心……'],
      idle: ['敷十五分鐘就好，不要笑，會裂。', '要不要試試看？'],
      rival: ['你的臉需要敷三層！', '哼，醜小鴨。'],
      friend: ['你今天好美！', '送你一罐泥漿面膜！'],
      refuse: '這樣我連泥都買不起！明明泥是免費的……',
    },
  }),
  T({
    id: 'gz-coffee', name: '阿豐', shopName: '東山青農咖啡', shopType: 'cafe',
    traits: ['shy', 'hardworking'], skill: 3, maxRentTier: 0,
    intro: '我……我在東山種咖啡。家裡的咖啡樹是阿公留下來的。想……想讓更多人喝到。',
    look: look({ skin: 0xc98e66, hair: 0x2a1d17, hairStyle: 'short', shirt: 0x6b4a3a, pants: 0x6d5a4a, accessory: 'hat', age: 'young' }),
    arrive: { minDay: 10 },
    lines: {
      hello: '（小聲）謝、謝謝……我會好好煮的。',
      happy: ['有客人說喝得出龍眼木的香味！', '今天豆子都賣完了。'],
      unhappy: ['我還是回山上種樹好了……', '（默默擦杯子）'],
      idle: ['這支是日曬的……', '要不要……試喝？'],
      rival: ['……', '我只是想好好煮咖啡……'],
      friend: ['這杯……請你。', '跟你聊天不會緊張。'],
      refuse: '這個……我的咖啡樹會哭……',
    },
  }),
  T({
    id: 'gz-cai', name: '阿財', shopName: '財神伴手禮', shopType: 'souvenir',
    traits: ['stingy', 'online'], skill: 4, maxRentTier: 2,
    intro: '會長！做生意就是要看到別人看不到的。我看你們山上那團火燒了三百年，都沒人拿來賺錢，可惜啊！',
    look: look({ skin: 0xe8b48f, hair: 0x111111, hairStyle: 'short', shirt: 0xd9a03b, pants: 0x2b2b2b, accessory: 'none', age: 'mid' }),
    arrive: { flag: 'caiArrived' },
    lines: {
      hello: '合作愉快！有錢大家賺！',
      happy: ['今天賺得比昨天多！', '財神爺有保佑！'],
      unhappy: ['虧錢的生意我不做！', '這條街是不是被詛咒了……'],
      idle: ['要不要來一盒「水火同源」伴手禮？', '買三送一，只有今天！'],
      rival: ['你這種做法不會賺錢的啦。', '我出錢，你出力，就這麼簡單。'],
      friend: ['跟著我，有肉吃！', '下次有好康的先找你！'],
      refuse: '這個價錢我寧願去隔壁鄉開店。',
    },
  }),
];

const stories: StoryEvent[] = [
  {
    id: 'gz-intro', street: ST, once: true, priority: 99, when: 'morning',
    cond: () => ({}),
    script: () => [
      narrate('台南白河，關子嶺。山腰上的溫泉老街，空氣裡飄著淡淡的硫磺味。'),
      focus({ landmark: 'spring' }),
      appear('gzChief', { landmark: 'spring' }),
      appear('me', { landmark: 'spring' }, -90),
      say('gzChief', '會長，歡迎來到關子嶺！九份的林理事長一直跟我說你很厲害。'),
      say('gzChief', '你看這個露頭，灰灰黑黑的泥漿溫泉，全世界沒幾個地方有。日本時代跟北投、陽明山、四重溪並列台灣四大溫泉喔。'),
      emote('me', 'star'),
      say('gzChief', '不過……老實講，這個露頭的水，只夠幾間湯屋、旅館用。開越多溫泉店，水就越不夠分。'),
      say('gzChief', '可以再開新的泉井，但山上的里民很在意，開太多會被罵。'),
      emote('gzChief', 'sweat'),
      focus({ landmark: 'fire' }),
      say('gzChief', '再過去是「水火同源」。石縫裡水跟天然氣一起冒出來，火燒了幾百年都不會熄。'),
      narrate('提示：點「寶泉橋露頭」可以查看泉量、開新泉井；點「水火同源」可以決定要不要拿來做生意。'),
      leave('gzChief'), leave('me'),
    ],
  },
  {
    id: 'gz-water-first', street: ST, once: true, priority: 70, when: 'noon',
    cond: (c) => {
      if (springRatio(c.s) >= 1) return null;
      const a = c.present.find((id) => isSpringShop(c.s, c.s.lots.findIndex((l) => l.shop?.tenantId === id)));
      return a ? { a } : null;
    },
    script: (b) => [
      focus(b.a),
      appear(b.a),
      say(b.a, '會長！水怎麼越來越溫了！客人泡到一半跑出來說是「溫開水」！'),
      emote(b.a, 'anger'),
      appear('gzChief', b.a, 120),
      say('gzChief', '溫泉店開太多，露頭的水不夠分了。每家湯屋、旅館都要用水。'),
      say('gzChief', '要嘛少開幾家溫泉店，要嘛在露頭旁邊開新的泉井……不過開井，里民會有意見。'),
      choice('泉水不夠用了',
        opt('先送點禮安撫一下', { sat: [[b.a, 8]] }, [say(b.a, '好啦……但水的問題要趕快解決喔！')], 800),
        opt('我會想辦法', { sat: [[b.a, -2]] }, [say(b.a, '想辦法要快啊……'), emote(b.a, 'sweat')]),
      ),
      narrate('提示：點「寶泉橋露頭」可以開新泉井，泉量會增加，但民怨也會上升。'),
      leave(b.a), leave('gzChief'),
    ],
  },
  {
    id: 'gz-cai-arrive', street: ST, once: true, priority: 40, when: 'morning',
    cond: (c) => (c.s.day >= 4 ? {} : null),
    script: () => [
      effect({ flag: ['caiArrived'], applicant: ['gz-cai'] }),
      narrate('佈告欄來了一位眼睛發亮的生意人：「財神伴手禮」阿財。'),
    ],
  },
  {
    id: 'gz-chicken-war', street: ST, cooldown: 7, chance: 0.6, priority: 30, when: 'noon',
    cond: (c) => (c.has('gz-chicken') && c.has('gz-chicken2') ? {} : null),
    script: () => [
      narrate('兩家甕缸雞門口，同時掛上了新招牌……'),
      focus('gz-chicken'),
      appear('gz-chicken'),
      say('gz-chicken', '「關子嶺元祖甕仔雞」！大家看清楚，元祖在這！'),
      appear('gz-chicken2', 'gz-chicken', 140),
      say('gz-chicken2', '「正宗元祖窯烤雞・始祖認證」！我還有我阿公的老照片！'),
      emote('gz-chicken', 'anger'),
      emote('gz-chicken2', 'anger'),
      appear('tourist', 'gz-chicken', 70),
      say('tourist', '……所以到底哪一家才是元祖啦？我只是想吃雞。'),
      emote('tourist', 'sweat'),
      choice('元祖之戰又開打了',
        opt('辦「盲測烤雞大賽」，讓客人決定', { rel: [['gz-chicken', 'gz-chicken2', 20]], rep: 2, buff: { id: 'chickenCup', name: '烤雞大賽', days: 2, mods: { shopAppeal: { claypot: 1.25 } } } }, [
          fx('confetti', 'tourist'),
          narrate('盲測結果……兩家只差一票！兩個人互看一眼，竟然笑了。'),
          say('gz-chicken', '……你的皮烤得不錯。'),
          say('gz-chicken2', '……甕伯的醃料還是比較香。'),
        ], 3000),
        opt('元祖不重要，好吃最重要', { rel: [['gz-chicken', 'gz-chicken2', -8]] }, [
          say('gz-chicken', '哼！'),
          say('gz-chicken2', '哼！'),
        ]),
      ),
      leave('gz-chicken'), leave('gz-chicken2'), leave('tourist'),
    ],
  },
  {
    id: 'gz-queue', street: ST, once: true, priority: 28, when: 'noon',
    cond: (c) => {
      const id = c.present.find((t) => c.shopOf(t)?.defId === 'claypot');
      if (!id) return null;
      const i = c.s.lots.findIndex((l) => l.shop?.tenantId === id);
      const n = [i - 1, i + 1].map((j) => c.s.lots[j]?.shop?.tenantId).find(Boolean);
      return n ? { a: id, b: n } : null;
    },
    script: (b) => [
      narrate('中午，甕缸雞門口排起長長的人龍……'),
      focus(b.a),
      appear(b.b),
      say(b.b, '欸！排隊的人都擋到我家門口了啦！我的客人進不來！'),
      emote(b.b, 'anger'),
      appear(b.a, b.b, 120),
      say(b.a, '我也沒辦法啊，客人要排，我能叫他們不要吃嗎？'),
      choice('排隊人龍擋到隔壁了',
        opt('發號碼牌，叫號再回來', { flag: ['queueTickets'], rel: [[b.a, b.b, 10]], rep: 1 }, [
          say(b.a, '好啦，抽號碼牌，先去逛逛，叫到再回來！'),
          say(b.b, '欸，排隊的人跑來我這邊買東西了！'),
          emote(b.b, 'star'),
        ], 2000),
        opt('請大家互相體諒', { rel: [[b.a, b.b, -10]] }, [say(b.b, '體諒？我的店都快被淹沒了！')]),
      ),
      leave(b.a), leave(b.b),
    ],
  },
  {
    id: 'gz-buyout', street: ST, once: true, priority: 45, when: 'evening',
    cond: (c) => (c.s.day >= 6 && c.has('gz-ryokan') && c.has('gz-ceo') ? {} : null),
    script: (_b, c) => [
      narrate('傍晚，嶺泉館門口來了一位穿西裝的年輕人……'),
      focus('gz-ryokan'),
      appear('gz-ryokan'),
      appear('gz-ceo', 'gz-ryokan', 130),
      say('gz-ceo', '秀子姨，我直接說了。嶺泉館的招牌、建築、歷史，我全部買下來，改成精品 villa。價錢你開。'),
      say('gz-ryokan', '……少年仔，你知道這間厝，阮阿祖顧了幾年嗎？'),
      say('gz-ceo', '一百二十年。所以它值得被更多人看見，而不是慢慢老去。'),
      emote('gz-ryokan', 'anger'),
      appear('me', 'gz-ryokan', -110),
      choice('Jason 想收購嶺泉館',
        ...(c.rel('gz-ryokan', 'gz-ceo') > -30
          ? [opt('撮合兩人合作：老旅館＋新行銷', { rel: [['gz-ryokan', 'gz-ceo', 30]], sat: [['gz-ryokan', 5], ['gz-ceo', 5]], rep: 2 }, [
            say('gz-ryokan', '……招牌不能改。泥湯的泡法，也要照阮的規矩。'),
            say('gz-ceo', 'Deal！我負責讓全世界知道，你負責守住它。'),
            emote('gz-ryokan', 'heart'),
          ])]
          : []),
        opt('支持老店：招牌不能賣', { sat: [['gz-ryokan', 12], ['gz-ceo', -10]], rel: [['gz-ryokan', 'gz-ceo', -10]] }, [
          say('gz-ryokan', '會長，多謝你。'),
          say('gz-ceo', '……好，我會用我的方式證明。'),
          emote('gz-ceo', 'sad'),
        ]),
        opt('支持收購：讓老旅館轉型', { takeOver: ['gz-ryokan', 'gz-villa', 2], sat: [['gz-ceo', 15]], rep: -3 }, [
          narrate('秀子姨默默收拾了阿祖的老照片。「嶺泉館」的木招牌被拆了下來，換上「泥月 Villa」。'),
          say('gz-ceo', '秀子姨，房子我會好好保留。等你想回來泡湯，永遠有一間房留給你。'),
          narrate('嶺泉館變成 Jason 經營的精品溫泉旅館「泥月 Villa」。原本的裝修和方案都留著，租金也改成高價。'),
        ]),
      ),
      leave('gz-ryokan'), leave('gz-ceo'), leave('me'),
    ],
  },
  {
    id: 'gz-graymask', street: ST, cooldown: 8, chance: 0.5, priority: 15, when: 'noon',
    cond: (c) => (c.present.find((t) => c.shopOf(t)?.defId === 'mudspa') ? { a: c.present.find((t) => c.shopOf(t)?.defId === 'mudspa')! } : null),
    script: (b) => [
      focus(b.a),
      appear('tourist', b.a, 60),
      say('tourist', '（臉上敷滿灰色泥漿）哈囉～我剛剛敷完臉～'),
      appear('tourist2', b.a, 160),
      say('tourist2', '哇啊啊啊！有殭屍！'),
      emote('tourist2', 'shock'),
      appear(b.a),
      say(b.a, '那不是殭屍，那是美麗的過程！'),
      choice('泥漿臉嚇到人了',
        opt('在門口掛「敷臉中，請勿驚慌」', { rep: 1, sat: [[b.a, 5]] }, [say('tourist2', '……原來是面膜。我也要敷！'), emote('tourist2', 'star')]),
        opt('請客人洗完臉再出門', { sat: [[b.a, -5]] }, [say(b.a, '可是……灰色的臉才是招牌啊……')]),
      ),
      leave('tourist'), leave('tourist2'), leave(b.a),
    ],
  },
  {
    id: 'gz-haohan-race', street: ST, cooldown: 9, chance: 0.4, priority: 10, when: 'noon',
    cond: (c) => (c.present.length >= 3 ? {} : null),
    script: () => [
      focus({ landmark: 'haohan' }),
      appear('tourist', { landmark: 'haohan' }, -40),
      appear('tourist2', { landmark: 'haohan' }, 40),
      say('tourist2', '少年仔，來比賽！看誰先爬上好漢坡！'),
      say('tourist', '阿伯你確定嗎？兩百七十階耶！'),
      fx('smoke', 'tourist2'),
      narrate('十分鐘後……'),
      say('tourist', '（喘）阿伯……你怎麼……還在跑……'),
      say('tourist2', '阮少年時，日本兵在這裡操練，阮阿爸天天爬！'),
      emote('tourist2', 'star'),
      effect({ rep: 1 }),
      leave('tourist'), leave('tourist2'),
    ],
  },
  {
    id: 'gz-yukata-photo', street: ST, once: true, priority: 25, when: 'noon',
    cond: (c) => (c.has('gz-yukata') && c.s.reputation >= 20 ? {} : null),
    script: () => [
      focus({ landmark: 'haohan' }),
      appear('festGuest', { landmark: 'haohan' }),
      fx('flash', 'festGuest'),
      say('festGuest', '穿浴衣站在好漢坡上面，背景是整片山……這張一定爆！'),
      appear('gz-yukata', 'festGuest', 120),
      say('gz-yukata', '對對對，再往左一點，回頭看鏡頭！完美！'),
      fx('flash', 'gz-yukata'),
      narrate('「關子嶺浴衣散步」在網路上爆紅了！'),
      effect({ rep: 2, sat: [['gz-yukata', 10]], buff: { id: 'yukataViral', name: '浴衣散步爆紅', days: 4, mods: { traffic: 1.1, shopAppeal: { yukata: 1.3 } } } }),
      leave('festGuest'), leave('gz-yukata'),
    ],
  },
  {
    id: 'gz-ryokan-heir', street: ST, once: true, priority: 60, when: 'morning',
    cond: (c) => (c.has('gz-ryokan') && c.sat('gz-ryokan') < 30 && c.s.day >= 5 ? {} : null),
    script: (_b, c) => [
      narrate('一早，嶺泉館的門沒有開……'),
      focus('gz-ryokan'),
      appear('gz-mountain', 'gz-ryokan', 60),
      appear('me', 'gz-ryokan', -60),
      say('gz-mountain', '會長！秀子昨晚累倒了，送去新營的醫院。醫生說要休息一陣子……'),
      say('gz-mountain', '她兒子在美國，孫子在台北上班，嶺泉館……沒人可以接了。'),
      emote('me', 'sad'),
      choice('嶺泉館沒有人接班',
        opt('補助請人幫忙顧店', { sat: [['gz-ryokan', 30]] }, [
          say('gz-mountain', '好、好，阿嬤也會每天過去幫忙煮早餐。'),
          emote('gz-mountain', 'heart'),
        ], 6000),
        ...(c.has('gz-yukata') ? [opt('請小葵幫忙顧（她最愛日式老屋）', { sat: [['gz-ryokan', 20], ['gz-yukata', 5]], rel: [['gz-ryokan', 'gz-yukata', 30]] }, [
          appear('gz-yukata', 'gz-ryokan', 140),
          say('gz-yukata', '真的可以嗎！我會好好照顧它的！浴衣客人也可以直接入住！'),
        ])] : []),
        ...(c.has('gz-ceo') ? [opt('讓 Jason 接手經營', { takeOver: ['gz-ryokan', 'gz-villa', 2] as [string, string, number], sat: [['gz-ceo', 10]], rep: -1 }, [
          appear('gz-ceo', 'gz-mountain', 140),
          say('gz-ceo', '交給我吧。房子、泥湯的泡法，我都照秀子姨的規矩來。'),
          narrate('嶺泉館由 Jason 接手，改名「泥月 Villa」。'),
        ])] : []),
        opt('沒辦法了……', { leave: ['gz-ryokan'], rep: -3 }, [
          narrate('嶺泉館，熄燈了。'),
        ]),
      ),
      leave('gz-mountain'), leave('gz-yukata'), leave('gz-ceo'), leave('me'),
    ],
  },
  {
    id: 'gz-wait', street: ST, once: true, priority: 50, when: 'morning',
    cond: (c) => {
      if (c.s.quake) return null;
      const others = c.street.goals.filter((g) => g.id !== 'spring');
      return others.every((g) => g.check(c.s)) ? {} : null;
    },
    script: () => [
      focus({ landmark: 'spring' }),
      appear('gzChief', { landmark: 'spring' }),
      say('gzChief', '會長，關子嶺好久沒這麼熱鬧了！不過……'),
      say('gzChief', '水伯說，這陣子露頭的聲音怪怪的。再撐一下，看看接下來會怎麼樣。'),
      emote('gzChief', 'sweat'),
      leave('gzChief'),
    ],
  },
  {
    id: 'gz-ending', street: ST, once: true, priority: 95, when: 'morning',
    cond: (c) => (c.street.goals.every((g) => g.check(c.s)) ? {} : null),
    script: () => [
      narrate('關子嶺的泉水，又咕嘟咕嘟地冒著泡了。'),
      focus({ landmark: 'spring' }),
      appear('gzChief', { landmark: 'spring' }),
      appear('gzAuntie', { landmark: 'spring' }, 110),
      appear('me', { landmark: 'spring' }, -100),
      say('gzAuntie', '會長，一開始我很怕你把山挖空。後來看你有在聽大家的話……'),
      say('gzAuntie', '共同浴場那池水，阮老人家天天去泡。多謝你。'),
      emote('gzAuntie', 'heart'),
      say('gzChief', '地震那天大家互相幫忙的樣子，我一輩子都會記得。'),
      say('gzChief', '對了，我收到一封信。東山那邊有一條很偏僻的老街——東原老街。他們說……什麼資源都沒有。'),
      emote('me', 'idea'),
      say('gzChief', '那是很難的一條路。不過今天，先去泡個湯吧。'),
      fx('firecracker', 'me'),
      narrate('第三章完成！下一站：東原老街……敬請期待。'),
      effect({ chapterComplete: true }),
      leave('gzAuntie'), leave('gzChief'), leave('me'),
    ],
  },
];

export const GUANZILING: StreetDef = {
  id: ST,
  name: '關子嶺老街',
  region: '台南市白河區',
  difficulty: 3,
  tagline: '泥漿溫泉・妖怪祭典',
  intro: '日治時期與北投、陽明山、四重溪並列台灣四大溫泉。灰黑色的泥漿溫泉全世界少見，山上還有「水火同源」的不滅之火。老街只剩短短一段，老旅館撐著百年招牌，年輕人想回來開店，卻發現溫泉水不夠分……',
  map: { x: 0.45, y: 0.655 },
  playable: true,
  facade: 'onsen',
  backdrop: 'hot-spring',
  ground: 'stone',
  layout: [
    { kind: 'landmark', id: 'haohan' },
    { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' },
    { kind: 'landmark', id: 'spring' },
    { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' },
    { kind: 'landmark', id: 'fire' },
    { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' },
    { kind: 'landmark', id: 'fireshrine' },
  ],
  landmarks: [
    { id: 'haohan', name: '好漢坡', description: '日本時代軍隊操練體能修的石階，連接老街和上面的嶺頂。爬上去的人下來會又累又餓。', width: 280 },
    { id: 'spring', name: '寶泉橋露頭', description: '泥漿溫泉從地面湧出的地方。點擊可以查看泉量、開新泉井。', width: 300 },
    { id: 'fire', name: '水火同源', description: '石縫裡水和天然氣一起冒出，火燒了幾百年不熄（實際位在老街上方的山區）。點擊可以決定怎麼經營。', width: 340 },
    { id: 'fireshrine', name: '火王爺廟', description: '供奉火王爺的小廟，守護水火同源的火。', width: 220 },
  ],
  startLots: 4,
  startMoney: 35000,
  startRep: 10,
  baseTraffic: 14,
  repTraffic: 0.9,
  weekendMult: 2.0,
  rentMult: 1.3,
  maintenance: 500,
  lotCost: 10000,
  weather: { rain: 0.2, fog: 0.05 },
  visitors: { jp: 0, kr: 0 },
  closeHour: 22,
  festivalCloseHour: 26,
  spring: { base: 12, wellCost: [10000, 18000, 28000, 42000], wellYield: 3 },
  quakeDay: 18,
  shopTypes: ['claypot', 'ryokan', 'bathhouse', 'mudspa', 'onsenegg', 'yukata', 'sanchan', 'cafe', 'souvenir', 'grocery'],
  tenants,
  stories: [...stories, ...GUANZILING_EVENTS, ...GUANZILING_FEST],
  activities: {
    templeFair: { name: '火王爺遶境', temple: '火王爺廟' },
    mascots: [
      { id: 'mudboy', name: '泥泥', description: '灰色泥漿做成的小人，走過的地方留下泥腳印。休閒類 +15%。', mods: { appeal: { leisure: 1.15 } } },
      { id: 'chick', name: '甕仔雞仔', description: '頂著甕缸的小雞，跟著香味跑。吃的店 +12%。', mods: { appeal: { food: 1.12 } } },
      { id: 'flame', name: '火王仔', description: '水火同源的小火苗精靈，晚上會發光。人潮 +8%。', mods: { traffic: 1.08 } },
    ],
    legends: [
      { id: 'beauty', name: '泥漿美顏', description: '「泡了關子嶺泥湯，皮膚年輕十歲。」溫和可信，幾乎不會出事。', risk: 0.05, mods: { appeal: { leisure: 1.15 } } },
      { id: 'wish', name: '對火許願必中', description: '「對水火同源許願，考試一定過！」很有效，也很容易被拆穿。', risk: 0.45, mods: { traffic: 1.2 } },
    ],
  },
  goals: [
    { id: 'rep', text: '聲望達到 70', check: (s) => s.reputation >= 70 },
    { id: 'shops', text: '同時有 8 家店營業', check: (s) => shops(s) >= 8 },
    { id: 'fest', text: '天下第一鼎成功一次', check: (s) => s.flags.includes('cauldronOk') },
    { id: 'spring', text: '震後泉量恢復到震前的 80%', check: (s) => springRecovered(s) },
    { id: 'calm', text: '民怨低於 40', check: (s) => s.grievance < 40 },
  ],
  next: 'dongyuan',
};
