import type { StreetDef, TenantProfile, StoryEvent, GameState } from '../core/types';
import { say, emote, narrate, focus, appear, walk, leave, fx, effect, choice, opt, look } from './dsl';
import { JIUFEN_EVENTS } from './jiufenEvents';
import { JIUFEN_NIGHT } from './jiufenNight';

const ST = 'jiufen';
const shops = (s: GameState) => s.lots.filter((l) => l.shop).length;
const buddies = (s: GameState) => Object.values(s.relations).filter((v) => v >= 40).length;

const T = (t: Omit<TenantProfile, 'street'>): TenantProfile => ({ ...t, street: ST });

const tenants: TenantProfile[] = [
  T({
    id: 'jf-taro', name: '芋仔嬸', shopName: '嬸婆芋圓', shopType: 'taro',
    traits: ['veteran', 'hothead'], skill: 5, maxRentTier: 2,
    intro: '我在九份搓芋圓搓四十年了！手比機器還準！不過我先講，隔壁不准租給那個賣魚丸的！',
    look: look({ skin: 0xe8b48f, hair: 0x4a4a4a, hairStyle: 'bun', shirt: 0x7a4a9a, pants: 0x3d3a36, accessory: 'apron', age: 'old' }),
    relations: { 'jf-fish': -55, 'jf-gui': 30 },
    lines: {
      hello: '好！今天開始搓！',
      happy: ['芋圓賣到手痠！', '排隊排到豎崎路了啦！'],
      unhappy: ['這樣下去我要收攤了！', '氣到芋圓都搓歪了！'],
      idle: ['熱的還是冰的？', '芋圓要現煮才 Q！'],
      rival: ['你那個魚丸是冷凍的啦！', '三十年前的事我還記得！'],
      friend: ['來，這碗算我的！', '老姊妹，晚上來我家吃飯。'],
      refuse: '你當我芋圓是金子做的喔？',
    },
  }),
  T({
    id: 'jf-fish', name: '魚丸伯', shopName: '海伯魚丸湯', shopType: 'fishball',
    traits: ['veteran', 'stubborn'], skill: 4, maxRentTier: 1,
    intro: '……魚丸。手打的。湯是大骨熬八小時。還有，那個搓芋圓的，欠我一個道歉。',
    look: look({ skin: 0xc98e66, hair: 0xd9d4cc, hairStyle: 'short', shirt: 0x2f6f8f, pants: 0x3d3a36, accessory: 'headband', age: 'old' }),
    relations: { 'jf-taro': -55 },
    lines: {
      hello: '……嗯。',
      happy: ['……今天的湯，有甜。', '客人喝到碗底朝天，好。'],
      unhappy: ['……哼。', '這種日子，不如回去討海。'],
      idle: ['湯要趁熱。', '九份的雨，配魚丸湯剛好。'],
      rival: ['……我不跟你計較。', '你的芋圓才是冷凍的。'],
      friend: ['……多給你一顆。', '坐。'],
      refuse: '……太貴。不租。',
    },
  }),
  T({
    id: 'jf-tea', name: '月娘', shopName: '月見茶樓', shopType: 'teahouse',
    traits: ['creative', 'dramatic'], skill: 4, maxRentTier: 2,
    intro: '這座山城的夜，紅燈籠一盞盞亮起……我想讓每位客人在茶香裡，看見屬於自己的那片海。',
    look: look({ skin: 0xf9dcc4, hair: 0x111111, hairStyle: 'long', shirt: 0xb3262e, pants: 0x2b2b3a, accessory: 'none', age: 'mid' }),
    relations: { 'jf-ocarina': 15 },
    lines: {
      hello: '願我們的緣分，如這壺茶般回甘。',
      happy: ['今夜的燈籠，特別溫柔。', '客人說看見了海……我好感動。'],
      unhappy: ['茶涼了……人心也涼了……', '或許，我該離開這座山城。'],
      idle: ['這是金萱，有奶香。', '霧來了，真美。'],
      rival: ['俗不可耐。', '請別打擾我的客人品茶。'],
      friend: ['來，為你沏一壺好茶。', '有你在，九份更美了。'],
      refuse: '這價格……一點也不詩意。',
    },
  }),
  T({
    id: 'jf-ocarina', name: '阿笛', shopName: '笛聲工房', shopType: 'ocarina',
    traits: ['shy', 'creative'], skill: 3, maxRentTier: 1,
    intro: '我……我會做陶笛，也會吹……但是有人看的時候我會緊張到吹不出聲音……',
    look: look({ skin: 0xf5d0b0, hair: 0x2a1d17, hairStyle: 'spiky', shirt: 0xe9e2d0, pants: 0x6d5a4a, accessory: 'scarf', age: 'young' }),
    relations: { 'jf-tea': 15 },
    lines: {
      hello: '（小聲）請、請多指教……',
      happy: ['今天有人跟我一起吹！', '♪～'],
      unhappy: ['我還是回去當工程師好了……', '（默默擦陶笛）'],
      idle: ['這個是 12 孔的……', '要、要試吹嗎？'],
      rival: ['……', '我只是想安靜做笛子……'],
      friend: ['這首曲子送給你。', '跟你在一起不會緊張。'],
      refuse: '這個……我要賣好多支笛子……',
    },
  }),
  T({
    id: 'jf-gui', name: '粿姨', shopName: '金粿草仔粿', shopType: 'caogui',
    traits: ['friendly', 'gossip'], skill: 3, maxRentTier: 1,
    intro: '唉唷會長你好年輕喔！粿姨的草仔粿是用艾草跟鼠麴草做的，吃了身體勇健！',
    look: look({ skin: 0xf2c9a5, hair: 0x7a5232, hairStyle: 'bob', shirt: 0x6abf69, pants: 0x54627a, accessory: 'apron', age: 'mid' }),
    relations: { 'jf-taro': 30 },
    lines: {
      hello: '大家要好好相處喔～',
      happy: ['今天的粿特別香！', '唉唷，又賣完了！'],
      unhappy: ['粿都放到硬了……', '最近好像大家都不開心……'],
      idle: ['你知道嗎，聽說……', '甜的鹹的都有喔！'],
      rival: ['唉唷，你怎麼這樣講話。', '我是看你可憐才不說的。'],
      friend: ['這兩個給你帶回去～', '我們是好姊妹！'],
      refuse: '唉唷，這樣粿姨會被房租壓扁啦～',
    },
  }),
  T({
    id: 'jf-gold', name: '金伯', shopName: '金礦伴手禮', shopType: 'souvenir',
    traits: ['veteran', 'gossip'], skill: 3, maxRentTier: 1,
    intro: '我阿公是挖金仔的。九份當年有多風光你知道嗎？坐下來，我講給你聽，大概講三個鐘頭。',
    look: look({ skin: 0xc98e66, hair: 0xd9d4cc, hairStyle: 'bald', shirt: 0x5b5f73, pants: 0x3d3a36, accessory: 'hat', age: 'old' }),
    arrive: { minDay: 3 },
    lines: {
      hello: '好，換我來講古了。',
      happy: ['今天又有人聽我講完了！', '金仔沒挖到，客人挖到不少！'],
      unhappy: ['現在的人都不聽古了……', '唉，九份的金光不再囉。'],
      idle: ['以前九份叫小上海你知道嗎？', '這個礦工帽，有故事的。'],
      rival: ['你懂什麼九份！', '我在這裡的時候你還沒出生！'],
      friend: ['我講一個只跟你講的故事。', '來來來，坐。'],
      refuse: '這租金比當年的金價還貴！',
    },
  }),
  T({
    id: 'jf-mike', name: 'Mike', shopName: "Mike's 九份 Café", shopType: 'cafe',
    traits: ['online', 'friendly'], skill: 3, maxRentTier: 2,
    intro: '你好！我是 Mike，從加拿大來的。我愛九份，我愛芋圓，我愛……下雨？不，我不愛下雨。',
    look: look({ skin: 0xf9dcc4, hair: 0xd9a03b, hairStyle: 'short', shirt: 0x4f86c6, pants: 0x7a8a6a, accessory: 'cap', age: 'young' }),
    arrive: { minRep: 25 },
    lines: {
      hello: '我們是好鄰居！好～鄰～居！',
      happy: ['今天好多客人！我好感動到哭哭！', 'Amazing！九份 number one！'],
      unhappy: ['我想念楓糖漿……', '為什麼這裡一直下雨？'],
      idle: ['你吃飽了嗎？我學會了這句！', '要拿鐵還是……芋圓拿鐵？'],
      rival: ['你很……不 nice。', 'Why are you like this？'],
      friend: ['Bro！你是我最好的朋友！', '我做了芋圓鬆餅給你！'],
      refuse: 'Sorry，太貴了，我的錢包會哭。',
    },
  }),
  T({
    id: 'jf-fu', name: '阿福', shopName: '九份柑仔店', shopType: 'grocery',
    traits: ['lazy', 'friendly'], skill: 2, maxRentTier: 0,
    intro: '我爸叫我出來做生意……那我就開個柑仔店吧，坐著顧店就好，應該不難吧？',
    look: look({ skin: 0xe8b48f, hair: 0x111111, hairStyle: 'short', shirt: 0xf0f0f0, pants: 0x2f3550, accessory: 'none', age: 'young' }),
    lines: {
      hello: '好喔～那我先睡一下。',
      happy: ['今天有賺錢欸，不錯不錯。', '嘿嘿，客人自己找錢。'],
      unhappy: ['好累喔……', '要不要乾脆收起來……'],
      idle: ['zzz……啊？要買什麼？', '彈珠汽水一瓶 30。'],
      rival: ['好啦好啦你說的都對。', '不要吵，我在睡覺。'],
      friend: ['送你一包乖乖。', '一起偷懶吧。'],
      refuse: '這麼貴我要很認真才付得起，算了。',
    },
  }),
  T({
    id: 'jf-xiaoyu', name: '小芋', shopName: '芋見你', shopType: 'taro',
    traits: ['online', 'dramatic'], skill: 3, maxRentTier: 2,
    intro: '我做的是「芋圓 2.0」！芋泥流心、彩虹芋圓、芋圓珍奶！傳統？可以吃嗎？',
    look: look({ skin: 0xf9dcc4, hair: 0x9b6bc9, hairStyle: 'ponytail', shirt: 0xef8fb1, pants: 0xf0f0f0, accessory: 'none', age: 'young' }),
    arrive: { minRep: 30 },
    relations: { 'jf-taro': -20 },
    lines: {
      hello: '我會讓九份芋圓上熱搜！',
      happy: ['彩虹芋圓被分享一千次了！', '我就說會紅吧～'],
      unhappy: ['為什麼大家還是去排老店……', '我要崩潰了！'],
      idle: ['這款有加芋泥喔！', '幫我按讚好不好？'],
      rival: ['老人家就是跟不上時代！', '你那個芋圓三十年都沒變過！'],
      friend: ['師父～我的芋圓有進步嗎？', '一起拍影片！'],
      refuse: '這個價格，網紅也撐不住啦！',
    },
  }),
  T({
    id: 'jf-lan', name: '嵐姐', shopName: '山嵐民宿', shopType: 'minshuku',
    traits: ['friendly', 'hardworking'], skill: 4, maxRentTier: 1,
    intro: '我們家三樓的窗戶可以看到整片海！早上起來泡杯茶，雲就在腳下。住過的客人都說捨不得走～',
    look: look({ skin: 0xf2c9a5, hair: 0x4a3324, hairStyle: 'bun', shirt: 0x6b8f6b, pants: 0x54627a, accessory: 'apron', age: 'mid' }),
    lines: {
      hello: '房間我已經打掃好了，隨時歡迎！',
      happy: ['今晚又客滿啦！', '客人說我的早餐比飯店好吃～'],
      unhappy: ['空房好多……', '昨晚客人說隔壁太吵，唉。'],
      idle: ['要不要上來看看房間？', '晚上的燈籠從窗戶看出去超美。'],
      rival: ['你可以小聲一點嗎？我的客人在睡覺！', '半夜還在吵，很沒公德心耶。'],
      friend: ['我的客人早上都去你那吃早餐喔！', '有空來喝杯茶～'],
      refuse: '這個租金，我要天天客滿才付得起啦。',
    },
  }),
  T({
    id: 'jf-wu', name: '霧先生', shopName: '霧宿 Fog Inn', shopType: 'minshuku',
    traits: ['creative', 'stubborn'], skill: 4, maxRentTier: 2,
    intro: '我的民宿只有四間房，每一間都是我親手設計的。濃霧的夜晚，窗外什麼都看不見——那才是最美的時候。',
    look: look({ skin: 0xf5d0b0, hair: 0x111111, hairStyle: 'long', shirt: 0x2b2b2b, pants: 0x3d3a36, accessory: 'glasses', age: 'young' }),
    arrive: { minRep: 25 },
    lines: {
      hello: '請別在我的民宿門口大聲喧嘩。',
      happy: ['今晚霧很好。', '客人懂我的設計，很欣慰。'],
      unhappy: ['……太吵了。我需要安靜。', '這不是我想要的九份。'],
      idle: ['霧，是九份的呼吸。', '入住請脫鞋。'],
      rival: ['你的燈籠太亮了。', '噪音是一種暴力。'],
      friend: ['你懂安靜的價值。', '霧大的晚上，來喝一杯。'],
      refuse: '……不。',
    },
  }),
  T({
    id: 'jf-ama', name: '阿嬤', shopName: '阿嬤的厝', shopType: 'minshuku',
    traits: ['veteran', 'gossip'], skill: 3, maxRentTier: 0,
    intro: '阮厝是礦工時代留落來的老厝啦，房間細細間，毋過阿嬤會煮地瓜稀飯予人客食。',
    look: look({ skin: 0xe8b48f, hair: 0xd9d4cc, hairStyle: 'bun', shirt: 0xb3262e, pants: 0x3d3a36, accessory: 'none', age: 'old' }),
    arrive: { minDay: 4 },
    lines: {
      hello: '人客來，阿嬤歡迎啦！',
      happy: ['昨暝的人客講阮厝足有古早味！', '地瓜稀飯攏食了了！'],
      unhappy: ['人客愈來愈少喔……', '阿嬤老囉，樓梯爬袂起來。'],
      idle: ['你敢知影以前礦工攏住佇遮？', '半暝毋通烏白走喔，霧內底有物件。'],
      rival: ['你真正無禮貌！', '少年仔，莫遮爾大聲。'],
      friend: ['來，食一碗稀飯。', '你是好囡仔。'],
      refuse: '阿嬤無遐爾濟錢啦。',
    },
  }),
];

const stories: StoryEvent[] = [
  {
    id: 'jf-intro', street: ST, once: true, priority: 100, when: 'morning',
    cond: (c) => (c.s.day === 1 ? {} : null),
    script: () => [
      narrate('新北市瑞芳區・九份老街'),
      focus({ landmark: 'viewpoint' }),
      appear('jfChief', { landmark: 'viewpoint' }),
      appear('me', { landmark: 'viewpoint' }, -90),
      say('jfChief', '歡迎來到九份！你看，從這裡可以看到基隆山跟整片海。'),
      emote('me', 'star'),
      say('jfChief', '九份不缺遊客，缺的是……秩序。'),
      say('jfChief', '基山街很窄，人一多就塞。店家租金高，脾氣也大。'),
      emote('jfChief', 'sweat'),
      say('jfChief', '尤其是賣芋圓的跟賣魚丸的那兩位……唉，你遇到就知道了。'),
      say('me', '……我好像接了一個不得了的工作。'),
      say('jfChief', '加油！霧大的時候記得慢慢走，豎崎路的石階很滑。'),
      leave('jfChief'),
      effect({ flag: ['intro'], unlockActivity: ['templeFair'] }),
    ],
  },
  {
    id: 'jf-feud', street: ST, once: true, priority: 80, when: 'morning',
    cond: (c) => (c.has('jf-taro') && c.has('jf-fish') ? {} : null),
    script: (_b, c) => [
      narrate('九份三十年恩怨'),
      focus('jf-taro'),
      appear('jf-taro'),
      appear('jf-fish', 'jf-taro', 150),
      say('jf-taro', '你還敢來九份開店！三十年前你打翻我一整鍋芋圓！'),
      say('jf-fish', '……不是我。我說過幾百次了。'),
      emote('jf-taro', 'anger'),
      emote('jf-fish', 'anger'),
      appear('me', 'jf-taro', 75),
      say('me', '等等……這件事已經吵了三十年？'),
      choice('要怎麼處理三十年恩怨？',
        opt('辦「芋圓魚丸大對決」讓遊客評審', { rel: [['jf-taro', 'jf-fish', 25]],
          buff: { id: 'foodDuel', name: '芋圓魚丸大對決', days: 2, mods: { traffic: 1.3, appeal: { food: 1.25 } } } }, [
          fx('confetti', 'jf-taro'),
          narrate('遊客們吃得很開心……結果是「鹹甜都好吃」。'),
          say('jf-fish', '……你的芋圓，還是一樣 Q。'),
          say('jf-taro', '哼……你的湯，還是一樣鮮。'),
        ], 4000),
        opt('調查三十年前的真相', { rel: [['jf-taro', 'jf-fish', 50]], rep: 1, flag: ['feudSolved'] }, [
          ...(c.has('jf-gold') ? [
            appear('jf-gold', 'jf-taro', -140),
            say('jf-gold', '那件事啊……我記得很清楚。'),
            say('jf-gold', '是一隻橘色的貓跳上攤子，把鍋子踢翻的啦！'),
          ] : [
            appear('cat', 'jf-taro', -120),
            narrate('一隻橘貓緩緩走過……旁邊的老鄰居突然想起來——'),
            narrate('當年打翻芋圓的，是一隻橘貓！'),
          ]),
          emote('jf-taro', 'shock'),
          emote('jf-fish', 'shock'),
          say('jf-taro', '……那我罵你罵了三十年？'),
          say('jf-fish', '……嗯。'),
          say('jf-taro', '對不起啦！今天芋圓我請！'),
          emote('jf-taro', 'heart'),
          emote('jf-fish', 'heart'),
          fx('confetti', 'jf-fish'),
        ]),
        opt('讓他們自己吵', { rel: [['jf-taro', 'jf-fish', -10]], rep: -1 }, [
          say('jf-taro', '好！再吵三十年！'),
          narrate('……看來會長也拿他們沒辦法。'),
        ]),
      ),
      leave('jf-taro'), leave('jf-fish'), leave('me'), leave('jf-gold'), leave('cat'),
    ],
  },
  {
    id: 'jf-spirited', street: ST, once: true, priority: 60, when: 'noon',
    cond: (c) => (c.has('jf-tea') ? {} : null),
    script: () => [
      focus('jf-tea'),
      appear('jf-tea'),
      appear('tourist', 'jf-tea', -120),
      appear('tourist2', 'jf-tea', -170),
      say('tourist', '請問！這間是不是那部動畫電影裡的茶屋？'),
      say('tourist2', '對對對，我們專程坐飛機來的！'),
      emote('jf-tea', 'sweat'),
      appear('me', 'jf-tea', 90),
      choice('觀光客一直問，月娘看著你……',
        opt('順勢說「是喔～就是這裡」', { buff: { id: 'spirited', name: '動畫聖地', days: 3, mods: { shopAppeal: { teahouse: 1.6 }, traffic: 1.1 } }, flag: ['lied'] }, [
          say('tourist', '哇啊啊啊！拍照拍照！'),
          fx('flash', 'tourist'),
          emote('jf-tea', 'sweat'),
          say('jf-tea', '……我的良心，有點苦。'),
        ]),
        opt('老實說「不是，但夜景一樣美」', { rep: 2, sat: [['jf-tea', 8]] }, [
          say('tourist', '原來不是喔……可是燈籠真的好美！'),
          say('jf-tea', '謝謝你，會長。誠實是一壺好茶。'),
          emote('jf-tea', 'heart'),
        ]),
        opt('推出「山城夜景限定茶套餐」', { rep: 1, sat: [['jf-tea', 12]], buff: { id: 'nightTea', name: '夜景茶套餐', days: 4, mods: { shopAppeal: { teahouse: 1.4 } } } }, [
          say('jf-tea', '好主意……夜霧、燈籠、一壺老茶……我來寫菜單！'),
          emote('jf-tea', 'idea'),
          fx('sparkle', 'jf-tea'),
        ], 1500),
      ),
      leave('tourist'), leave('tourist2'), leave('jf-tea'), leave('me'),
    ],
  },
  {
    id: 'jf-lie-exposed', street: ST, once: true, priority: 70, chance: 0.5, when: 'morning',
    cond: (c) => (c.flag('lied') && c.has('jf-tea') ? {} : null),
    script: () => [
      focus('jf-tea'),
      appear('reporter', 'jf-tea', -120),
      fx('flash', 'reporter'),
      say('reporter', '獨家！九份茶樓自稱動畫聖地，其實毫無關係！'),
      appear('jf-tea'),
      emote('jf-tea', 'shock'),
      say('jf-tea', '我、我從來沒有這樣說過……'),
      narrate('新聞上了熱搜……'),
      effect({ rep: -4, sat: [['jf-tea', -10]] }),
      leave('reporter'), leave('jf-tea'),
    ],
  },
  {
    id: 'jf-concert', street: ST, once: true, priority: 50, when: 'noon',
    cond: (c) => (c.has('jf-ocarina') && c.sat('jf-ocarina') >= 40 && c.s.day >= 3 ? {} : null),
    script: (_b, c) => [
      focus({ landmark: 'stairs' }),
      appear('jf-ocarina', { landmark: 'stairs' }),
      appear('me', { landmark: 'stairs' }, -90),
      say('jf-ocarina', '會長……其實我一直想在豎崎路的石階上吹陶笛……'),
      say('jf-ocarina', '可是想到有人在看，我就……'),
      emote('jf-ocarina', 'sweat'),
      choice('要鼓勵阿笛嗎？',
        opt('「我陪你！就吹一首就好」', { sat: [['jf-ocarina', 20]],
          buff: { id: 'ocarinaLive', name: '石階陶笛演奏', days: 3, mods: { traffic: 1.12, shopAppeal: { ocarina: 1.7, teahouse: 1.2 } } } }, [
          emote('jf-ocarina', 'music'),
          narrate('♪ 悠揚的笛聲在山城的石階間迴盪……'),
          emote('jf-ocarina', 'music'),
          appear('tourist', { landmark: 'stairs' }, 120),
          emote('tourist', 'heart'),
          ...(c.has('jf-tea') ? [
            appear('jf-tea', { landmark: 'stairs' }, 190),
            say('jf-tea', '……好美的聲音。以後每晚都來茶樓吹，好嗎？'),
            effect({ rel: [['jf-tea', 'jf-ocarina', 30]] }),
            emote('jf-ocarina', 'heart'),
          ] : []),
          say('jf-ocarina', '我……我做到了！'),
          fx('sparkle', 'jf-ocarina'),
        ]),
        opt('「下次再說吧，不要勉強」', { sat: [['jf-ocarina', -3]] }, [
          say('jf-ocarina', '……嗯，下次。'),
        ]),
      ),
      leave('jf-ocarina'), leave('me'), leave('tourist'), leave('jf-tea'),
    ],
  },
  {
    id: 'jf-gold-light', street: ST, once: true, priority: 45, when: 'evening',
    cond: (c) => (c.has('jf-gold') ? {} : null),
    script: () => [
      focus({ landmark: 'mine' }),
      appear('jf-gold', { landmark: 'mine' }),
      appear('me', { landmark: 'mine' }, -90),
      say('jf-gold', '會長，你知道九份為什麼叫九份嗎？'),
      say('jf-gold', '早年山上只住九戶人家，每次下山採買都要「九份」，就這樣叫下來了。'),
      say('jf-gold', '後來挖到金仔，整座山晚上都亮晶晶的……'),
      fx('sparkle', { landmark: 'mine' }),
      emote('me', 'star'),
      choice('要請金伯擔任老街說書人嗎？',
        opt('請金伯每天在礦車旁講古', { sat: [['jf-gold', 20]], rep: 2,
          buff: { id: 'goldTales', name: '金伯講古', days: 5, mods: { traffic: 1.12, appeal: { retail: 1.2, leisure: 1.15 } } } }, [
          say('jf-gold', '哈哈哈！講三個鐘頭都沒問題！'),
          emote('jf-gold', 'music'),
        ], 2000),
        opt('聽完故事就好', { sat: [['jf-gold', 5]] }, [
          say('jf-gold', '好啦，有空再來聽。'),
        ]),
      ),
      leave('jf-gold'), leave('me'),
    ],
  },
  {
    id: 'jf-mike-menu', street: ST, once: true, priority: 40, when: 'noon',
    cond: (c) => (c.has('jf-mike') ? {} : null),
    script: () => [
      focus('jf-mike'),
      appear('jf-mike'),
      appear('me', 'jf-mike', -80),
      say('jf-mike', '會長！我做了中文菜單！你看！'),
      narrate('菜單上寫著：「命運的芋頭球」「悲傷的熱拿鐵」「爸爸不在家鬆餅」'),
      emote('me', 'sweat'),
      say('jf-mike', '很好對吧？Google 說很好。'),
      choice('要怎麼辦？',
        opt('幫他改成正確的中文', { sat: [['jf-mike', 10]] }, [
          say('jf-mike', '喔～原來「爸爸不在家」不是 Daddy\'s Home 的意思！謝謝！'),
          emote('jf-mike', 'heart'),
        ]),
        opt('保留！觀光客會覺得很好笑', { rep: 1, buff: { id: 'funnyMenu', name: '爆笑菜單', days: 5, mods: { shopAppeal: { cafe: 1.4 } } } }, [
          appear('tourist', 'jf-mike', 120),
          say('tourist', '哈哈哈哈「悲傷的熱拿鐵」！我要點這個！'),
          fx('flash', 'tourist'),
          say('jf-mike', '？？？為什麼大家在笑？但是很多客人！好！'),
        ]),
      ),
      leave('jf-mike'), leave('me'), leave('tourist'),
    ],
  },
  {
    id: 'jf-taro-new', street: ST, once: true, priority: 55, when: 'morning',
    cond: (c) => (c.has('jf-taro') && c.has('jf-xiaoyu') ? {} : null),
    script: () => [
      narrate('新舊芋圓之爭'),
      focus('jf-xiaoyu'),
      appear('jf-xiaoyu'),
      appear('jf-taro', 'jf-xiaoyu', -150),
      say('jf-xiaoyu', '大家快來！彩虹流心芋圓！拍照超好看～'),
      say('jf-taro', '什麼彩虹！芋圓就是芋頭色！你這是在糟蹋芋頭！'),
      emote('jf-taro', 'anger'),
      say('jf-xiaoyu', '阿嬸，時代在變啦！你那個芋圓三十年都沒變！'),
      emote('jf-xiaoyu', 'anger'),
      appear('me', 'jf-xiaoyu', -70),
      choice('兩代芋圓店吵起來了……',
        opt('提議她們合作：師徒聯名芋圓', { rel: [['jf-taro', 'jf-xiaoyu', 45]], rep: 2, flag: ['taroMaster'],
          buff: { id: 'taroCollab', name: '師徒聯名芋圓', days: 4, mods: { shopAppeal: { taro: 1.4 } } } }, [
          say('jf-taro', '……哼，你的手法太浮了。明天早上五點來我店裡。'),
          say('jf-xiaoyu', '真的嗎？！師父！'),
          emote('jf-xiaoyu', 'heart'),
          emote('jf-taro', 'sweat'),
          fx('confetti', 'jf-taro'),
        ]),
        opt('支持老店，傳統才是九份', { sat: [['jf-taro', 15], ['jf-xiaoyu', -15]], rel: [['jf-taro', 'jf-xiaoyu', -10]] }, [
          say('jf-taro', '聽到沒！會長是識貨的！'),
          emote('jf-xiaoyu', 'sad'),
        ]),
        opt('支持新店，創新才有未來', { sat: [['jf-xiaoyu', 15], ['jf-taro', -15]], rel: [['jf-taro', 'jf-xiaoyu', -10]] }, [
          say('jf-xiaoyu', '耶！會長最潮了！'),
          emote('jf-taro', 'anger'),
        ]),
      ),
      leave('jf-taro'), leave('jf-xiaoyu'), leave('me'),
    ],
  },
  {
    id: 'jf-fog', street: ST, cooldown: 6, chance: 0.6, priority: 20, when: 'noon',
    cond: (c) => ((c.s.weather === 'fog' || c.s.weather === 'heavyFog') && c.present.length >= 2 ? { a: c.present[Math.floor(c.rand() * c.present.length)] } : null),
    script: (b) => [
      narrate('濃霧籠罩山城……'),
      focus(b.a),
      appear('tourist2', b.a, -140),
      say('tourist2', '咦？我剛剛不是走過這家店了嗎？怎麼又回來了？'),
      emote('tourist2', 'sweat'),
      appear(b.a),
      say(b.a, '大哥，你已經第三圈了啦。'),
      choice('要不要在霧天加派人手帶路？',
        opt('在路口掛導覽燈籠', { rep: 1, buff: { id: 'fogLanterns', name: '霧天導覽燈籠', days: 10, mods: { traffic: 1.05 } } }, [
          say('tourist2', '喔～有燈籠就不會迷路了！'),
          fx('sparkle', b.a),
        ], 2500),
        opt('順便推薦他進店坐坐', { sat: [[b.a, 5]] }, [
          say('tourist2', '好啦好啦，走累了，進來坐一下。'),
          walk('tourist2', b.a),
        ]),
      ),
      leave('tourist2'), leave(b.a),
    ],
  },
  {
    id: 'jf-ending', street: ST, once: true, priority: 95, when: 'morning',
    cond: (c) => (c.street.goals.every((g) => g.check(c.s)) ? {} : null),
    script: () => [
      narrate('九份的燈籠，從來沒有這麼亮過。'),
      focus({ landmark: 'viewpoint' }),
      appear('jfChief', { landmark: 'viewpoint' }),
      appear('me', { landmark: 'viewpoint' }, -90),
      say('jfChief', '會長，謝謝你。九份的店家現在會互相介紹客人了。'),
      say('jfChief', '我收到台南關子嶺溫泉老街的來信，他們也想請你過去……'),
      emote('me', 'idea'),
      say('jfChief', '不過那是下一段旅程了。今晚，先好好看看這片夜景吧。'),
      fx('firecracker', 'me'),
      narrate('第二章完成！下一站：台南關子嶺溫泉老街。'),
      effect({ chapterComplete: true }),
    ],
  },
];

export const JIUFEN: StreetDef = {
  id: ST,
  name: '九份老街',
  region: '新北市瑞芳區',
  difficulty: 2,
  tagline: '紅燈籠山城・遊客多到塞爆',
  intro: '曾因金礦繁華一時的山城。基山街窄小、豎崎路石階陡峭，遊客爆量、租金也高。挑戰是擠滿的人潮、霧雨天氣，還有店家之間的陳年恩怨。',
  map: { x: 0.8, y: 0.085 },
  playable: true,
  facade: 'jiufen',
  backdrop: 'mountain-sea',
  ground: 'stone',
  layout: [
    { kind: 'landmark', id: 'viewpoint' },
    { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' },
    { kind: 'landmark', id: 'stairs' },
    { kind: 'lot' }, { kind: 'lot' },
    { kind: 'landmark', id: 'theater' },
    { kind: 'lot' }, { kind: 'lot' },
    { kind: 'landmark', id: 'mine' },
    { kind: 'lot' }, { kind: 'lot' },
  ],
  landmarks: [
    { id: 'viewpoint', name: '觀景台', description: '可以遠眺基隆山與太平洋的觀景台，傍晚的海景最迷人。', width: 340 },
    { id: 'stairs', name: '豎崎路石階', description: '縱貫山坡、超過三百階的石階路，兩旁茶樓林立、紅燈籠高掛。', width: 280 },
    { id: 'theater', name: '昇平戲院', description: '日治時期興建的老戲院，是九份繁華年代的見證。', width: 320 },
    { id: 'mine', name: '礦坑與台車', description: '百年礦坑口與運礦台車，訴說著淘金年代的故事。', width: 300 },
  ],
  startLots: 4,
  startMoney: 30000,
  startRep: 15,
  baseTraffic: 18,
  repTraffic: 1,
  weekendMult: 1.8,
  rentMult: 1.6,
  maintenance: 600,
  lotCost: 12000,
  weather: { rain: 0.2, fog: 0.16, heavyFog: 0.12 },
  kamikakushi: 0.45,
  visitors: { jp: 0.3, kr: 0.2 },
  transport: { base: 50, name: '上山公車' },
  shopTypes: ['taro', 'teahouse', 'fishball', 'caogui', 'ocarina', 'souvenir', 'cafe', 'grocery', 'minshuku'],
  closeHour: 25,
  tenants,
  stories: [...stories, ...JIUFEN_EVENTS, ...JIUFEN_NIGHT],
  activities: {
    templeFair: { name: '九份廟會遶境', temple: '山城廟宇' },
    mascots: [
      { id: 'taroCat', name: '芋圓喵', description: '芋頭色的胖貓，尾巴是一串芋圓。人潮額外 +8%。', mods: { traffic: 1.08 } },
      { id: 'lantern', name: '燈籠仔', description: '會發光的紅燈籠精靈，晚上特別受歡迎。休閒類 +15%。', mods: { appeal: { leisure: 1.15 } } },
      { id: 'goldMouse', name: '金礦鼠', description: '戴著礦工帽的小老鼠，到處找金子。零售類 +15%。', mods: { appeal: { retail: 1.15 } } },
    ],
    legends: [
      { id: 'nine', name: '九戶人家九份貨', description: '九份地名由來的老故事，溫馨可信，幾乎不會出事。', risk: 0.05, mods: { appeal: { retail: 1.1 } } },
      { id: 'goldlight', name: '摸礦車會發財', description: '「摸過八番坑台車的人都中過發票！」很誇張，很有效，也很容易被拆穿。', risk: 0.45, mods: { traffic: 1.2 } },
    ],
  },
  goals: [
    { id: 'rep', text: '聲望達到 65', check: (s) => s.reputation >= 65 },
    { id: 'shops', text: '同時有 8 家店營業', check: (s) => shops(s) >= 8 },
    { id: 'revenue', text: '老街累積營收 $600,000', check: (s) => s.totalRevenue >= 600000 },
    { id: 'mascot', text: '推出老街吉祥物', check: (s) => !!s.mascot },
    { id: 'buddies', text: '街上出現 3 對「好麻吉」', check: (s) => buddies(s) >= 3 },
  ],
  next: 'guanziling',
};
