import type { StreetDef, TenantProfile, StoryEvent } from '../core/types';
import { say, emote, narrate, focus, appear, leave, fx, effect, choice, opt, look, wait } from './dsl';

const ST = 'shifen';

// =====================================================================
// 租客（全部虛構）
// =====================================================================

const T = (t: Omit<TenantProfile, 'street'>): TenantProfile => ({ ...t, street: ST });

const tenants: TenantProfile[] = [
  T({
    id: 'sf-gong', name: '天燈阿公', shopName: '阿公手作天燈', shopType: 'lantern',
    traits: ['veteran', 'stubborn'], skill: 5, maxRentTier: 1,
    intro: '我糊天燈糊了五十年。竹篾要削得剛剛好，紙要黏得一點縫都沒有，願望才不會漏出去。',
    look: look({ skin: 0xd9a27a, hair: 0xd9d4cc, hairStyle: 'short', shirt: 0xb3262e, pants: 0x3d3a36, accessory: 'none', age: 'old' }),
    relations: { 'sf-zhe': 20, 'sf-miner': 30 },
    lines: {
      hello: '好！明天開始，十分的天空交給我。',
      happy: ['你看那盞，飛得多正！', '今天的風剛剛好，燈都很聽話。'],
      unhappy: ['紙都受潮了……', '年輕人現在都只想拍照。'],
      idle: ['願望寫大一點，天公伯才看得到。', '四面都要寫，不要浪費。'],
      rival: ['你那個燈，飛不到電線杆就掉下來了啦。', '做天燈不是做網紅。'],
      friend: ['來，這盞給你，免錢。', '阿哲那孩子，其實手很巧。'],
      refuse: '這種租金，我要糊幾百盞才付得起？',
    },
  }),
  T({
    id: 'sf-zhe', name: '阿哲', shopName: '哲天燈 LAB', shopType: 'lantern',
    traits: ['online', 'creative'], skill: 3, maxRentTier: 2,
    intro: '我是天燈阿公的孫子！我想做會發光、會拍照打卡的天燈，讓全世界都知道十分。',
    look: look({ skin: 0xf2c9a5, hair: 0x2a1d17, hairStyle: 'spiky', shirt: 0x2b2b3a, pants: 0x54627a, accessory: 'cap', age: 'young' }),
    relations: { 'sf-gong': 20 },
    arrive: { flag: 'zheComing' },
    lines: {
      hello: '阿公，你等著看！我的天燈會上熱搜！',
      happy: ['這盞燈的限動有一萬人看！', '外國人都在問哪裡買！'],
      unhappy: ['為什麼大家還是只買阿公的……', '演算法不愛我了。'],
      idle: ['要不要幫你拍放天燈的慢動作？', '這是全台第一盞漸層天燈。'],
      rival: ['阿公，時代變了啦！', '老方法不一定比較好！'],
      friend: ['阿公，教我削竹篾。', '下次我們一起放一盞超大的！'],
      refuse: '這個價錢……我的業配還沒進來耶。',
    },
  }),
  T({
    id: 'sf-sisters', name: '天燈三姊妹', shopName: '三姊妹彩繪天燈', shopType: 'lantern',
    traits: ['friendly', 'creative'], skill: 4, maxRentTier: 1,
    intro: '我們三姊妹從小在阿公的店裡幫忙糊天燈。大姊畫圖、二姊寫字、小妹負責招呼客人！',
    look: look({ skin: 0xf6d6bd, hair: 0x2a1d17, hairStyle: 'ponytail', shirt: 0xf29ac0, pants: 0x54627a, accessory: 'none', age: 'young' }),
    relations: { 'sf-gong': 25, 'sf-zhe': 10 },
    arrive: { minDay: 5 },
    lines: {
      hello: '三個人一起顧店，速度是別人的三倍！',
      happy: ['今天畫了一百盞！手好痠但好開心！', '有客人指定要畫他家的狗！'],
      unhappy: ['顏料又用完了……', '二姊跟小妹又吵架了。'],
      idle: ['要畫什麼？我們都畫得出來！', '四面寫四個願望，最划算！'],
      rival: ['我們畫的比較好看啦！', '哼，不跟你好了。'],
      friend: ['送你一盞我們畫的！', '阿公說我們的燈飛最穩！'],
      refuse: '這個租金……三個人的薪水都不夠耶。',
    },
  }),
  T({
    id: 'sf-wing', name: '雞翅哥', shopName: '火車頭雞翅包飯', shopType: 'wingrice',
    traits: ['hardworking', 'hothead'], skill: 4, maxRentTier: 2,
    intro: '火車一進站，我十秒可以出十份。不是吹的，是練的。',
    look: look({ skin: 0xc98e66, hair: 0x111111, hairStyle: 'short', shirt: 0xf0f0f0, pants: 0x2b2b2b, accessory: 'headband', age: 'mid' }),
    relations: { 'sf-peanut': 25 },
    lines: {
      hello: '烤爐已經熱好了，什麼時候開賣？',
      happy: ['噹噹噹一響，翅膀就飛出去了！', '今天賣到手抽筋！'],
      unhappy: ['火車都不停我這邊……', '雞翅剩一堆。'],
      idle: ['裡面包炒飯，外面烤到脆。', '小心燙，邊走邊吃。'],
      rival: ['你的攤子擋到我的煙了！', '比速度？來啊！'],
      friend: ['雞翅配花生捲，絕配。', '幫你留一支最大的。'],
      refuse: '這個租金，我雞翅要賣到一支兩百才行。',
    },
  }),
  T({
    id: 'sf-peanut', name: '花生捲阿姨', shopName: '阿月花生捲', shopType: 'peanutroll',
    traits: ['friendly', 'gossip'], skill: 3, maxRentTier: 1,
    intro: '刨花生糖要用力，捲餅皮要輕。我在這條鐵軌旁邊刨了二十年。',
    look: look({ skin: 0xf2c9a5, hair: 0x4a3324, hairStyle: 'bun', shirt: 0xef8fb1, pants: 0x3d3a36, accessory: 'apron', age: 'mid' }),
    relations: { 'sf-wing': 25 },
    lines: {
      hello: '要不要加香菜？不加我也不會生氣啦。',
      happy: ['今天的花生糖刨得特別香。', '外國妹妹說這是台灣墨西哥捲餅，哈哈哈！'],
      unhappy: ['花生糖都快刨完了，還是沒什麼人……', '唉，膝蓋好酸。'],
      idle: ['你知道嗎，隔壁雞翅哥以前是貨運司機。', '香菜是靈魂啦！'],
      rival: ['你們家的油煙都飄過來了！', '不要再搶我的位子！'],
      friend: ['雞翅哥，等一下換你請我。', '來，試吃一口。'],
      refuse: '阿姨小本生意啦，這樣不行。',
    },
  }),
  T({
    id: 'sf-rail', name: '鐵道宅阿傑', shopName: '平溪線月台', shopType: 'railgoods',
    traits: ['creative', 'shy'], skill: 3, maxRentTier: 1,
    intro: '平溪線每一台車的編號我都背得出來。我想開一間店，讓大家知道這條線有多可愛。',
    look: look({ skin: 0xf6d6bd, hair: 0x2a1d17, hairStyle: 'short', shirt: 0x2f5f8f, pants: 0x3d3a36, accessory: 'glasses', age: 'young' }),
    lines: {
      hello: '請、請多指教……可以聽我介紹一下 DR1000 嗎？',
      happy: ['日本的鐵道迷買了整套車票！', '今天的車是我最喜歡的那一台！'],
      unhappy: ['大家只想拍照，不想聽我講……', '模型被摸到掉漆了。'],
      idle: ['平溪線一九二一年就通車了喔。', '這個是復古硬式車票。'],
      rival: ['那、那個……可以不要擋到月台嗎。', '……'],
      friend: ['這張車票送你，是我的珍藏。', '一起去拍晚上的末班車吧。'],
      refuse: '這個租金……我要賣掉我的收藏才付得起。',
    },
  }),
  T({
    id: 'sf-bamboo', name: '竹筒姐', shopName: '十分願竹', shopType: 'wishshop',
    traits: ['friendly', 'dramatic'], skill: 3, maxRentTier: 1,
    intro: '天燈飛走了，願望就看不到了。竹筒掛在這裡，下次來還找得到自己的願望。',
    look: look({ skin: 0xf5d0b0, hair: 0x111111, hairStyle: 'long', shirt: 0x6abf69, pants: 0x54627a, accessory: 'none', age: 'young' }),
    relations: { 'sf-gong': 15 },
    lines: {
      hello: '我會把整面牆都掛滿願望！',
      happy: ['今天又多了兩百個願望！', '有人回來找到三年前的竹筒，哭了耶！'],
      unhappy: ['竹子被雨淋到發霉了……', '牆都空空的。'],
      idle: ['寫完記得拍照喔。', '竹筒會跟著風叮叮咚咚響。'],
      rival: ['我的竹筒才不是天燈的備胎！', '哼。'],
      friend: ['幫你留一個最好的位置掛。', '阿公的天燈加我的竹筒，願望雙保險！'],
      refuse: '這樣我要賣好多竹筒才夠耶……',
    },
  }),
  T({
    id: 'sf-miner', name: '礦工嫂', shopName: '礦工嫂古早味', shopType: 'snack',
    traits: ['veteran', 'friendly'], skill: 4, maxRentTier: 0,
    intro: '我先生以前在礦坑做了三十年。我煮的，是以前送進礦坑的那種便當菜。',
    look: look({ skin: 0xc98e66, hair: 0xb7b1a8, hairStyle: 'bun', shirt: 0x5b5f73, pants: 0x3d3a36, accessory: 'apron', age: 'old' }),
    relations: { 'sf-gong': 30 },
    lines: {
      hello: '吃飽才有力氣放天燈。',
      happy: ['大家都說吃起來像外婆煮的。', '我先生今天也來幫忙了。'],
      unhappy: ['現在的人都吃快的……', '鍋子好重。'],
      idle: ['以前礦工下坑前，都要先吃一大碗。', '鐵軌那邊，以前是運煤的。'],
      rival: ['年輕人吃那個能飽嗎？', '……我不跟你計較。'],
      friend: ['來，多一顆滷蛋。', '阿公的天燈，是全十分最好的。'],
      refuse: '這個租金，我煮一整年都不夠。',
    },
  }),
  T({
    id: 'sf-yuki', name: 'Yuki', shopName: '線路旁咖啡', shopType: 'cafe',
    traits: ['creative', 'friendly'], skill: 3, maxRentTier: 2,
    intro: '我是從東京來的背包客，在十分放了一次天燈之後，就不想回去了。（用很努力的中文說）',
    look: look({ skin: 0xf9dcc4, hair: 0x6b4a30, hairStyle: 'bob', shirt: 0xe9e2d0, pants: 0x7a8a6a, accessory: 'camera', age: 'young' }),
    arrive: { minRep: 25 },
    lines: {
      hello: 'よろしくお願いします！請多多指教！',
      happy: ['日本的朋友都說要來！', '火車經過的時候，咖啡會一起抖，好可愛。'],
      unhappy: ['中文好難……', '大家都只是路過。'],
      idle: ['要不要拿鐵？上面可以拉一盞天燈。', '十分の空、最高です。'],
      rival: ['え……？', '我不太懂，但你好兇。'],
      friend: ['阿傑先生教我火車的名字！', '一起拍照吧！'],
      refuse: 'ごめんなさい……太貴了。',
    },
  }),
  T({
    id: 'sf-fish', name: '魚丸伯', shopName: '月台魚丸湯', shopType: 'fishball',
    traits: ['stubborn', 'veteran'], skill: 3, maxRentTier: 1,
    intro: '等火車的時候，喝一碗熱湯最好。我的魚丸是基隆來的，每天早上第一班車載上來。',
    look: look({ skin: 0xe8b48f, hair: 0x7a7a7a, hairStyle: 'short', shirt: 0x4f86c6, pants: 0x3d3a36, accessory: 'cap', age: 'old' }),
    lines: {
      hello: '湯一直滾著，隨時來。',
      happy: ['下雨天，湯賣到見底！', '今天的魚丸彈到可以打桌球。'],
      unhappy: ['天氣太熱，沒人要喝湯……', '腰痛。'],
      idle: ['魚丸要用手打。', '湯不要喝太快，燙。'],
      rival: ['你們那個捲餅，冷冰冰的。', '哼，湯才是正餐。'],
      friend: ['加一顆給你。', '晚上一起看天燈。'],
      refuse: '我這一碗才幾十塊啊。',
    },
  }),
  T({
    id: 'sf-gift', name: '天燈小舖老闆娘', shopName: '十分好禮', shopType: 'souvenir',
    traits: ['hardworking', 'gossip'], skill: 3, maxRentTier: 2,
    intro: '天燈鑰匙圈、天燈造型餅乾、天燈抱枕……只要是天燈，我都賣。',
    look: look({ skin: 0xf2c9a5, hair: 0x7a5232, hairStyle: 'ponytail', shirt: 0xf2b84b, pants: 0x3d3a36, accessory: 'none', age: 'mid' }),
    arrive: { minDay: 3 },
    lines: {
      hello: '放完天燈，記得帶一盞小的回家！',
      happy: ['天燈抱枕又補貨了！', '韓國團把整面牆買光了！'],
      unhappy: ['庫存堆到天花板了……', '怎麼都只逛不買。'],
      idle: ['這個天燈夜燈，插電就會亮喔。', '買三送一。'],
      rival: ['你們那邊價錢也太便宜了吧。', '搶客人喔？'],
      friend: ['新貨先給你挑。', '一起做聯名商品吧！'],
      refuse: '這種價錢，我抱枕要賣一千個。',
    },
  }),
];

// =====================================================================
// 劇情
// =====================================================================

const stories: StoryEvent[] = [
  {
    id: 'sf-intro', street: ST, once: true, priority: 100, when: 'morning',
    cond: (c) => (c.s.day === 1 ? {} : null),
    script: () => [
      narrate('新北市平溪區・十分老街'),
      focus({ landmark: 'station' }),
      appear('sfStation', { landmark: 'station' }),
      appear('me', { landmark: 'station' }, -90),
      say('sfStation', '你就是新來的會長？歡迎來到十分！我是站務員阿德。'),
      say('sfStation', '先跟你說最重要的事：這條街，火車是從正中間開過去的。'),
      emote('me', 'shock'),
      say('me', '正、正中間？'),
      say('sfStation', '對啊。平溪線差不多一個小時一班，每一班都倒一大車遊客進來。'),
      say('sfStation', '噹噹噹一響，在鐵軌上拍照的人就會跳開，擠進兩邊的店——大家都叫它「火車連擊」。'),
      appear('sf-gong', { landmark: 'station' }, 90),
      say('sf-gong', '還有天燈。在鐵軌上寫願望，放上天。一天放幾百盞，天空會整片都是燈。'),
      say('sf-gong', '會長，我想在這裡開一間天燈店。你看要不要租給我？'),
      emote('me', 'star'),
      say('me', '好！十分的天空，我們一起把它填滿！'),
      narrate('十分的遊客很多，不太需要擔心客人不夠。店開得越多、越好，火車連擊就越高。'),
      narrate('天燈店的客人會把天燈放上天。天上的燈越多，遠遠看到的人就越多。'),
      narrate('想要滿天都是燈，就多開幾間天燈店，再把它們整修升級。'),
      leave('sf-gong'), leave('sfStation'), leave('me'),
      effect({ applicant: ['sf-gong'], flag: ['intro'] }),
    ],
  },
  {
    id: 'sf-first-combo', street: ST, once: true, priority: 90, when: 'noon',
    cond: (c) => (c.s.bestCombo >= 5 ? {} : null),
    script: () => [
      focus({ landmark: 'station' }),
      appear('sfStation', { landmark: 'station' }),
      appear('me', { landmark: 'station' }, -90),
      say('sfStation', '會長，剛剛那班車你有看到嗎？火車一開過去，兩邊的店同時收錢！'),
      say('me', '叮叮叮叮的，好像打電動。'),
      say('sfStation', '哈哈哈！店越多、等級越高，連擊越長。聽說最高紀錄是三十連擊。'),
      fx('coins', 'me'),
      emote('me', 'star'),
      effect({ rep: 2, money: 1000 }),
      leave('sfStation'), leave('me'),
    ],
  },
  {
    id: 'sf-sky-full', street: ST, once: true, priority: 85, when: 'evening',
    cond: (c) => (c.s.skyGlow >= 80 ? {} : null),
    script: () => [
      narrate('傍晚。抬頭一看——'),
      focus({ landmark: 'bridge' }),
      appear('me', { landmark: 'bridge' }),
      appear('tourist', { landmark: 'bridge' }, 80),
      say('tourist', '哇……天空全部都是燈耶！'),
      fx('sparkle', 'me'),
      narrate('滿天天燈！遠在瑞芳的人都看得到，坐上平溪線往十分來了。'),
      emote('me', 'heart'),
      effect({ rep: 3, buff: { id: 'skyfull', name: '滿天天燈上新聞', days: 2, mods: { traffic: 1.25 } } }),
      leave('tourist'), leave('me'),
    ],
  },
  {
    id: 'sf-miner-tale', street: ST, once: true, priority: 70, when: 'noon',
    cond: (c) => (c.s.day >= 3 ? {} : null),
    script: () => [
      focus({ landmark: 'mine' }),
      appear('sfMiner', { landmark: 'mine' }),
      appear('me', { landmark: 'mine' }, -90),
      say('sfMiner', '少年欸，你知道天燈是怎麼來的嗎？'),
      say('sfMiner', '聽老一輩講，以前山裡有土匪，大家都躲進山裡。'),
      say('sfMiner', '等土匪走了，留在村子的人就放一盞燈上天，告訴山上的人：可以回家了。'),
      emote('me', 'sad'),
      say('sfMiner', '所以天燈啊，本來是「平安」的意思。不管寫什麼願望，最後都是希望大家平安回家。'),
      say('sfMiner', '後來我在礦坑做了三十年。每次下坑前，我太太都會放一盞。'),
      choice('要怎麼用阿土伯的故事？',
        opt('請阿土伯在老煤礦前講古', { rep: 3, buff: { id: 'tale', name: '礦工講古', days: 4, mods: { appeal: { leisure: 1.2 } } } }, [
          say('sfMiner', '好啊，反正我每天也是坐在那邊。'),
          emote('sfMiner', 'music'),
        ]),
        opt('把故事印在天燈的說明卡上', { rep: 2, buff: { id: 'tale', name: '天燈的由來', days: 4, mods: { shopAppeal: { lantern: 1.25 } } } }, [
          say('sfMiner', '印上去？哈哈，那我要算版稅喔。'),
        ]),
      ),
      leave('sfMiner'), leave('me'),
      effect({ flag: ['minerTale'] }),
    ],
  },
  {
    id: 'sf-wing-race', street: ST, once: true, priority: 75, when: 'noon',
    cond: (c) => (c.has('sf-wing') && c.has('sf-peanut') ? { a: 'sf-wing', b: 'sf-peanut' } : null),
    script: (b) => [
      narrate('十二點的那班車，就快進站了。'),
      focus(b.a),
      appear(b.a),
      appear(b.b, b.a, 130),
      say(b.a, '阿月姐，來比！火車開過去之前，看誰賣比較多份！'),
      say(b.b, '比就比，輸的請喝飲料！'),
      fx('flash', b.a),
      narrate('噹噹噹噹——！'),
      fx('coins', b.a),
      fx('coins', b.b),
      say(b.a, '十二份！'),
      say(b.b, '十四份！哈哈哈，花生捲比較好捲啦！'),
      emote(b.a, 'sweat'),
      emote(b.b, 'star'),
      say(b.a, '……下一班再比。'),
      effect({ rel: [[b.a, b.b, 20]], sat: [[b.a, 8], [b.b, 8]], rep: 1 }),
      leave(b.a), leave(b.b),
    ],
  },
  {
    id: 'sf-grandson', street: ST, once: true, priority: 80, when: 'morning',
    cond: (c) => (c.has('sf-gong') && c.s.day >= 4 ? { a: 'sf-gong' } : null),
    script: (b) => [
      focus(b.a),
      appear(b.a),
      appear('sf-zhe', b.a, 120),
      say('sf-zhe', '阿公！我回來了！我要在十分做「會發光的天燈」，拍起來超美！'),
      say(b.a, '發光？天燈本來就會發光啊，裡面有火。'),
      say('sf-zhe', '不是啦，是 LED 漸層、可以拍限動的那種！'),
      emote(b.a, 'anger'),
      say(b.a, '天燈是用來許願的，不是用來拍照的！'),
      appear('me', b.a, -100),
      choice('祖孫兩個吵起來了。會長要怎麼做？',
        opt('支持阿哲：讓他在老街開自己的天燈店', { flag: ['zheComing'], applicant: ['sf-zhe'], sat: [[b.a, -6]] }, [
          say('sf-zhe', '謝謝會長！阿公，你等著看！'),
          emote(b.a, 'sweat'),
          narrate('阿哲出現在招租佈告欄上了。'),
        ]),
        opt('支持阿公：天燈要照老方法做', { rep: 2, sat: [[b.a, 10]] }, [
          say(b.a, '會長懂我。'),
          say('sf-zhe', '……好啦，那我先幫阿公拍影片。'),
          narrate('阿哲幫阿公拍的「職人糊天燈」影片意外爆紅。'),
          effect({ buff: { id: 'zheVideo', name: '職人天燈影片爆紅', days: 3, mods: { traffic: 1.25, shopAppeal: { lantern: 1.2 } } } }),
        ]),
        opt('兩個都要：老手藝加新點子', { flag: ['zheComing'], applicant: ['sf-zhe'], sat: [[b.a, 4]], rep: 1 }, [
          say('me', '阿公教阿哲糊天燈，阿哲幫阿公拍成影片。兩間店，一起把天空填滿！'),
          say(b.a, '……竹篾要是削不好，我可是會罵人的。'),
          say('sf-zhe', '阿公最好了！'),
          emote(b.a, 'heart'),
          emote('sf-zhe', 'heart'),
        ]),
      ),
      leave('sf-zhe'), leave(b.a), leave('me'),
    ],
  },
  {
    id: 'sf-more-trains', street: ST, once: true, priority: 78, when: 'morning',
    cond: (c) => (c.s.reputation >= 30 && c.s.day >= 5 ? {} : null),
    script: () => [
      focus({ landmark: 'station' }),
      appear('sfStation', { landmark: 'station' }),
      appear('me', { landmark: 'station' }, -90),
      say('sfStation', '會長，好消息！台鐵說最近十分人太多，可以考慮「加班車」。'),
      say('sfStation', '只要老街出一點宣傳費，平日、假日都會再密一點。'),
      choice('要請台鐵加開班次嗎？',
        opt('加開！火車越多越好', { flag: ['moreTrains'], rep: 2 }, [
          say('sfStation', '太好了！以後平日四十五分鐘一班，假日半小時一班！'),
          fx('firecracker', 'sfStation'),
          narrate('平溪線加班車：火車更密，連擊次數變多了。'),
        ], 15000),
        opt('再等等', {}, [
          say('sfStation', '好，想好再跟我說。'),
          effect({ flag: ['trainsLater'] }),
        ]),
      ),
      leave('sfStation'), leave('me'),
    ],
  },
  {
    id: 'sf-more-trains-again', street: ST, once: true, priority: 60, when: 'morning',
    cond: (c) => (c.flag('trainsLater') && !c.flag('moreTrains') && c.s.money >= 30000 ? {} : null),
    script: () => [
      focus({ landmark: 'station' }),
      appear('sfStation', { landmark: 'station' }),
      say('sfStation', '會長，加班車的事，台鐵還在等你喔！'),
      choice('要請台鐵加開班次嗎？',
        opt('加開！', { flag: ['moreTrains'], rep: 2 }, [fx('firecracker', 'sfStation')], 15000),
        opt('還是算了', {}),
      ),
      leave('sfStation'),
    ],
  },
  {
    id: 'sf-festival', street: ST, once: true, priority: 82, when: 'morning',
    cond: (c) => (c.s.day >= 8 && (c.s.lanternBest >= 600 || c.s.day >= 12) ? {} : null),
    script: () => [
      focus({ landmark: 'station' }),
      appear('sfStation', { landmark: 'station' }),
      appear('sfMiner', { landmark: 'station' }, 90),
      appear('me', { landmark: 'station' }, -90),
      say('sfMiner', '會長，十分這麼熱鬧，該辦一次「元宵天燈節」了吧？'),
      say('sfStation', '天燈節那天，台鐵會加開好多班車。整條街的天燈都放雙倍！'),
      say('sfMiner', '晚上大家一起把燈放上去，像以前那樣。'),
      emote('me', 'idea'),
      narrate('解鎖活動：元宵天燈節！（在「活動」裡舉辦）'),
      effect({ unlockActivity: ['templeFair'] }),
      leave('sfMiner'), leave('sfStation'), leave('me'),
    ],
  },
  {
    id: 'sf-giant', street: ST, once: true, priority: 72, when: 'morning',
    cond: (c) => {
      const id = c.present.find((t) => c.shopOf(t)?.defId === 'lantern' && (c.shopOf(t)?.level ?? 0) >= 3);
      return id ? { a: id } : null;
    },
    script: (b) => [
      focus(b.a),
      appear(b.a),
      appear('me', b.a, -90),
      say(b.a, '會長，看！三公尺高的巨型天燈！'),
      say(b.a, '一盞要十個人一起撐，一次寫十個人的願望。'),
      fx('sparkle', b.a),
      emote('me', 'star'),
      narrate('三級天燈店，偶爾會有客人放巨型天燈（一次算 10 盞）。'),
      effect({ rep: 2 }),
      leave(b.a), leave('me'),
    ],
  },
  {
    id: 'sf-cat', street: ST, cooldown: 5, chance: 0.35, priority: 40, when: 'morning',
    cond: (c) => (c.s.day >= 3 ? {} : null),
    script: () => [
      focus({ landmark: 'station' }),
      appear('sfCat', { landmark: 'station' }),
      appear('sfStation', { landmark: 'station' }, 100),
      narrate('一隻橘貓沿著鐵軌，慢慢地散步過來。'),
      say('sfStation', '又是你！從猴硐搭火車過來的吧？'),
      emote('sfCat', 'zzz'),
      say('sfStation', '……算了，下一班車還有十分鐘，讓牠睡一下。'),
      narrate('遊客圍著貓拍照，貓咪照片在網路上傳開了。'),
      effect({ buff: { id: 'cat', name: '鐵軌上的橘貓', days: 2, mods: { traffic: 1.1 } } }),
      leave('sfCat'), leave('sfStation'),
    ],
  },
  {
    id: 'sf-rain', street: ST, cooldown: 3, priority: 45, when: 'morning',
    cond: (c) => (c.s.weather === 'rain' && c.has('sf-gong') ? { a: 'sf-gong' } : null),
    script: (b) => [
      focus(b.a),
      appear(b.a),
      say(b.a, '下雨天，天燈飛不起來。'),
      say(b.a, '那就讓客人進來，自己在天燈上畫畫。畫好了，等雨停再放。'),
      emote(b.a, 'idea'),
      narrate('雨天彩繪天燈：今天體驗類的店更受歡迎。'),
      effect({ buff: { id: 'rainpaint', name: '雨天彩繪天燈', days: 1, mods: { appeal: { leisure: 1.4 } } } }),
      leave(b.a),
    ],
  },
  {
    id: 'sf-wishes', street: ST, cooldown: 4, chance: 0.5, priority: 35, when: 'noon',
    cond: (c) => (c.present.some((t) => c.shopOf(t)?.defId === 'lantern') ? {} : null),
    script: () => [
      focus({ landmark: 'bridge' }),
      appear('tourist', { landmark: 'bridge' }),
      appear('tourist2', { landmark: 'bridge' }, 90),
      say('tourist', '你寫什麼？'),
      say('tourist2', '「希望老婆不要發現我又買了一台腳踏車」。'),
      say('tourist', '……這個寫在天燈上，會飛到全十分的人都看得到耶。'),
      emote('tourist2', 'shock'),
      wait(300),
      narrate('那盞天燈，飛得特別高。'),
      effect({ rep: 1 }),
      leave('tourist'), leave('tourist2'),
    ],
  },
  {
    id: 'sf-ending', street: ST, once: true, priority: 99, when: 'evening',
    cond: (c) => (c.street.goals.every((g) => g.check(c.s)) ? {} : null),
    script: () => [
      narrate('元宵節的晚上。十分老街的每一個人，都拿著一盞天燈走上鐵軌。'),
      focus({ landmark: 'bridge' }),
      appear('me', { landmark: 'bridge' }, -60),
      appear('sf-gong', { landmark: 'bridge' }, 30),
      appear('sf-zhe', { landmark: 'bridge' }, 110),
      appear('sfStation', { landmark: 'bridge' }, -150),
      appear('sfMiner', { landmark: 'bridge' }, 190),
      say('sfStation', '末班車剛走，今晚鐵軌是大家的！'),
      say('sf-zhe', '阿公，我們那盞巨型的，準備好了！'),
      say('sf-gong', '竹篾我削了三天。這盞燈，寫的是整條街的願望。'),
      say('sfMiner', '……還有，大家都平安回家。'),
      emote('sf-gong', 'heart'),
      narrate('三——'),
      narrate('二——'),
      narrate('一！'),
      fx('firecracker', 'me'),
      fx('sparkle', 'sf-gong'),
      fx('confetti', 'me'),
      narrate('上千盞天燈同時離開地面。紅的、黃的、粉紅的、藍的、八色的，把十分的夜空一格一格填滿。'),
      narrate('最後那盞巨型天燈慢慢升起，燈上寫著：「願十分，一直這麼亮。」'),
      say('sf-zhe', '……阿公，比我拍過的任何一張照片都美。'),
      say('sf-gong', '傻孩子，這種的，要用眼睛看。'),
      narrate('遠遠地，一班加開的火車鳴著笛開過來。車窗裡的乘客，全部抬著頭。'),
      emote('me', 'star'),
      narrate('十分老街完成！'),
      effect({ chapterComplete: true }),
      leave('sfMiner'), leave('sfStation'), leave('sf-zhe'), leave('sf-gong'), leave('me'),
    ],
  },
];

// =====================================================================
// 老街資料
// =====================================================================

export const LANTERN_GOAL = 3000;
export const COMBO_GOAL = 30;
export const REVENUE_GOAL = 8_000_000;

export const SHIFEN: StreetDef = {
  id: ST,
  name: '十分老街',
  region: '新北市平溪區',
  difficulty: 0.5,
  tagline: '火車穿過老街・滿天天燈',
  intro: '平溪線為了運煤開進山裡，煤挖完了，火車卻沒有停——現在它一車一車載來遊客。火車就從老街正中間開過去，遊客在鐵軌上寫願望、放天燈。人潮不會斷，錢一直跳，天空越來越滿。這一關，盡情地爽吧。',
  map: { x: 0.79, y: 0.15 },
  playable: true,
  facade: 'railside',
  backdrop: 'pingxi-valley',
  ground: 'rail',
  layout: [
    { kind: 'landmark', id: 'station' },
    { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' },
    { kind: 'landmark', id: 'bridge' },
    { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' },
    { kind: 'landmark', id: 'mine' },
    { kind: 'lot' }, { kind: 'lot' },
    { kind: 'landmark', id: 'falls' },
  ],
  landmarks: [
    { id: 'station', name: '十分車站', description: '平溪線上最大的車站。火車每一班都倒出一大波遊客。', width: 340 },
    { id: 'bridge', name: '靜安吊橋', description: '橫跨基隆河的吊橋，從上面看火車穿過老街最漂亮。', width: 300 },
    { id: 'mine', name: '老煤礦', description: '平溪線本來是為了運煤而建。礦坑口還留著運煤的小台車。', width: 280 },
    { id: 'falls', name: '十分瀑布', description: '台灣最大的簾幕式瀑布。（實際上要沿著步道走一段路）', width: 380 },
  ],
  startLots: 5,
  startMoney: 50000,
  startRep: 25,
  baseTraffic: 14,
  repTraffic: 0.5,
  weekendMult: 1.5,
  rentMult: 1.3,
  maintenance: 400,
  lotCost: 7000,
  closeHour: 22,
  weather: { rain: 0.18, fog: 0 },
  visitors: { jp: 0.22, kr: 0.18 },
  train: { interval: 60, weekendInterval: 45, first: 8.5, last: 21, burst: 24 },
  shopTypes: ['lantern', 'wingrice', 'peanutroll', 'railgoods', 'wishshop', 'snack', 'cafe', 'souvenir', 'fishball'],
  tenants,
  stories,
  activities: {
    templeFair: { name: '元宵天燈節', temple: '十分', desc: '全街一起辦天燈節！台鐵加開班次、人潮大增，當天每一位客人都放雙倍的天燈，晚上整條街一波一波地放燈。' },
    mascots: [
      { id: 'sfLantern', name: '小天燈', description: '一盞會飄來飄去的小天燈，肚子上寫著「好運」。天燈店 +20%。', mods: { shopAppeal: { lantern: 1.2 } } },
      { id: 'sfTrain', name: '平溪線小火車', description: '藍白色的小火車頭，嘟嘟嘟地跟遊客合照。人潮額外 +10%。', mods: { traffic: 1.1 } },
      { id: 'sfCart', name: '礦坑小台車', description: '載滿「黑金」（其實是巧克力）的運煤台車。零售類 +15%。', mods: { appeal: { retail: 1.15 } } },
    ],
    legends: [
      { id: 'high', name: '天燈飛得越高，願望越快實現', description: '溫和可信，幾乎不會出事。天燈店 +20%。', risk: 0.05, mods: { shopAppeal: { lantern: 1.2 } } },
      { id: 'home', name: '天燈是告訴山上的人：可以回家了', description: '有點感人，有點難證明。人潮 +15%。', risk: 0.2, mods: { traffic: 1.15 } },
    ],
  },
  goals: [
    { id: 'lanterns', text: `一天放出 ${LANTERN_GOAL} 盞天燈`, check: (s) => s.lanternBest >= LANTERN_GOAL || (s.today.lanterns ?? 0) >= LANTERN_GOAL },
    { id: 'combo', text: `火車連擊達到 ×${COMBO_GOAL}`, check: (s) => s.bestCombo >= COMBO_GOAL },
    { id: 'fest', text: '舉辦元宵天燈節', check: (s) => s.flags.includes('held-templeFair') },
    { id: 'revenue', text: '老街累積營收 $8,000,000', check: (s) => s.totalRevenue >= REVENUE_GOAL },
  ],
};
