import type { StreetDef, TenantProfile, StoryEvent } from '../core/types';
import { say, emote, narrate, focus, appear, walk, leave, fx, effect, choice, opt, look, wait } from './dsl';
import { homeFeelOk, isSunday, selfOrder } from '../core/zhongli';

const ST = 'zhongli';

// =====================================================================
// 租客（全部虛構）
// =====================================================================

const T = (t: Omit<TenantProfile, 'street'>): TenantProfile => ({ ...t, street: ST });

const tenants: TenantProfile[] = [
  T({
    id: 'zl-lan', name: '阿蘭', shopName: '阿蘭越南河粉', shopType: 'pho',
    traits: ['friendly', 'hardworking'], skill: 4, maxRentTier: 1,
    intro: '我從越南嫁來台灣二十年了。台語、越南話我都會講，誰需要翻譯就來找我。河粉的湯，我每天早上五點開始熬。',
    look: look({ skin: 0xe8c09a, hair: 0x1a1a1a, hairStyle: 'long', shirt: 0xd0a020, pants: 0x3d3a36, accessory: 'apron', age: 'mid' }),
    relations: { 'zl-uncle': 20, 'zl-dewi': 25 },
    lines: {
      hello: '會長，週日很忙喔，你要有心理準備！',
      happy: ['湯又賣完了！', '今天有小姐妹說，吃到跟媽媽煮的一樣。'],
      unhappy: ['週日人好多，我一個人忙不過來……', '隔壁說我們太吵了。'],
      idle: ['要加九層塔嗎？', 'Xin chào！河粉一碗嗎？'],
      rival: ['你怎麼可以這樣說她們！', '大家都是來工作的人啊。'],
      friend: ['阿伯，湯給你多一點。', '晚上一起吃飯吧。'],
      refuse: '這個租金……我要賣好多碗喔。',
    },
  }),
  T({
    id: 'zl-dewi', name: 'Dewi 姐', shopName: 'Warung Dewi 印尼小吃', shopType: 'warung',
    traits: ['friendly', 'veteran'], skill: 4, maxRentTier: 1,
    intro: '我以前也是看護，在台灣照顧阿公八年。後來留下來開店，煮家鄉的菜給還在工作的妹妹們吃。',
    look: look({ skin: 0xc8946a, hair: 0x2f6f5f, hairStyle: 'short', shirt: 0xd04040, pants: 0x3d3a36, accessory: 'hijab', age: 'mid' }),
    relations: { 'zl-lan': 25 },
    lines: {
      hello: 'Terima kasih！謝謝會長！',
      happy: ['沙爹烤了三百串！', '妹妹們吃飽了才有力氣回去工作。'],
      unhappy: ['齋戒月的時候，大家白天都餓著肚子工作……', '房東說要漲房租。'],
      idle: ['這是清真的喔，放心吃。', 'Mau makan apa？要吃什麼？'],
      rival: ['你不懂她們有多辛苦。', '……算了。'],
      friend: ['阿蘭姐，晚上來我這邊吃。', '辣椒醬送你一罐。'],
      refuse: '這樣我們的菜要賣很貴，妹妹們吃不起。',
    },
  }),
  T({
    id: 'zl-marites', name: 'Marites', shopName: "Marites' Sari-sari", shopType: 'sarisari',
    traits: ['gossip', 'friendly'], skill: 3, maxRentTier: 1,
    intro: '我嫁給台灣人，在中壢住了十五年。週日望完彌撒，大家都會來我店裡買零食、聊八卦。',
    look: look({ skin: 0xc98e66, hair: 0x2a1d17, hairStyle: 'ponytail', shirt: 0x3060c0, pants: 0x54627a, accessory: 'none', age: 'mid' }),
    lines: {
      hello: 'Salamat po！大家週日都會來！',
      happy: ['Joel 又在廣場唱歌了！', '今天的乾芒果賣光了！'],
      unhappy: ['好久沒回家了……', '有人說我們很吵。'],
      idle: ['這個 Skyflakes 是我們的國民餅乾。', 'Kumusta ka？'],
      rival: ['唉唷，你很兇耶。', '我們只是聊天比較大聲啦。'],
      friend: ['給你試吃一包！', '週日一起去彌撒？'],
      refuse: 'Ay，太貴了啦。',
    },
  }),
  T({
    id: 'zl-nan', name: '阿南', shopName: '阿南泰式廚房', shopType: 'thaifood',
    traits: ['hardworking', 'creative'], skill: 4, maxRentTier: 1,
    intro: '我在工地做了十二年。每個週日都在宿舍煮菜給大家吃，大家說我應該開店……我想試試看。',
    look: look({ skin: 0xb07a52, hair: 0x111111, hairStyle: 'short', shirt: 0x8050c0, pants: 0x3d3a36, accessory: 'cap', age: 'mid' }),
    arrive: { flag: 'nanDream' },
    lines: {
      hello: 'ขอบคุณครับ！謝謝會長！我會煮最好吃的打拋！',
      happy: ['大家說這是家裡的味道！', '涼拌木瓜辣到大家流眼淚，哈哈！'],
      unhappy: ['手上的傷又痛了……', '我想念媽媽。'],
      idle: ['要辣嗎？泰國辣喔。', '奶茶要不要？'],
      rival: ['我的菜沒有比較差。', '……'],
      friend: ['下次教你煮綠咖哩。', '週日一起唱歌！'],
      refuse: '我存的錢不夠付這個租金……',
    },
  }),
  T({
    id: 'zl-remit', name: '林大哥', shopName: '平安匯款', shopType: 'remit',
    traits: ['veteran', 'hardworking'], skill: 4, maxRentTier: 2,
    intro: '印尼話、越南話、菲律賓話、泰國話的「謝謝」「多少錢」「寄給誰」我都會。匯款這種事，要讓人放心。',
    look: look({ skin: 0xe8b48f, hair: 0x4a4a4a, hairStyle: 'short', shirt: 0x2f8f5f, pants: 0x2b2b2b, accessory: 'glasses', age: 'mid' }),
    lines: {
      hello: '每一筆錢，我都會好好幫大家寄到。',
      happy: ['今天有人寄錢回家給女兒繳學費。', '排隊的人都很有耐心。'],
      unhappy: ['窗口不夠，大家排到收假還排不到……', '有人被假匯款騙了，好心疼。'],
      idle: ['匯率今天不錯喔。', '收據要收好。'],
      rival: ['做生意要有良心。', '別坑人家的血汗錢。'],
      friend: ['幫我跟大家說，週日早點來排。', '晚上一起吃河粉。'],
      refuse: '這個租金太高了，我手續費不能再漲。',
    },
  }),
  T({
    id: 'zl-kai', name: '阿凱', shopName: '凱凱通訊', shopType: 'phoneshop',
    traits: ['online', 'friendly'], skill: 3, maxRentTier: 2,
    intro: '我爸媽以前也是從印尼來的華僑。儲值、換卡、修手機，大家週日最需要的就是跟家人視訊。',
    look: look({ skin: 0xe0b08a, hair: 0x2a1d17, hairStyle: 'spiky', shirt: 0xe07020, pants: 0x2b2b3a, accessory: 'none', age: 'young' }),
    lines: {
      hello: '網路要快，大家才看得到家人的臉！',
      happy: ['今天幫一個大哥修好手機，他馬上打給女兒，哭了。', '儲值卡賣到缺貨！'],
      unhappy: ['手機摔壞的人好多……', '網路好慢。'],
      idle: ['要儲值多少？', '這張卡打回印尼比較便宜。'],
      rival: ['你們那邊收費也太貴了吧。', '哼。'],
      friend: ['幫你手機貼膜，免費。', '一起去吃 Dewi 姐的沙爹！'],
      refuse: '這個租金，我要賣好多支手機。',
    },
  }),
  T({
    id: 'zl-mart', name: '陳老闆', shopName: '南洋大超市', shopType: 'asiamart',
    traits: ['stingy', 'veteran'], skill: 3, maxRentTier: 2,
    intro: '印尼泡麵、越南米紙、菲律賓醬油、泰國魚露，我這裡什麼都有。客人一週來一次，要一次買夠。',
    look: look({ skin: 0xe8b48f, hair: 0x7a7a7a, hairStyle: 'short', shirt: 0x20a080, pants: 0x3d3a36, accessory: 'none', age: 'old' }),
    arrive: { minDay: 3 },
    lines: {
      hello: '貨我都備好了，週日來搬吧。',
      happy: ['泡麵一箱一箱搬走！', '週日營業額是平日的十倍。'],
      unhappy: ['貨架被擠倒了……', '平日都沒人。'],
      idle: ['Indomie 一包二十。', '要不要買一箱比較划算？'],
      rival: ['價錢我最便宜。', '你們進的貨都過期了吧。'],
      friend: ['幫你留了一箱。', '下次一起進貨。'],
      refuse: '這種租金，我的利潤都沒了。',
    },
  }),
  T({
    id: 'zl-thu', name: '阿秋', shopName: '金星卡拉 OK', shopType: 'ktv',
    traits: ['dramatic', 'friendly'], skill: 3, maxRentTier: 1,
    intro: '我是越南新住民。週日晚上大家來唱家鄉的歌，唱一唱，就不那麼想家了。',
    look: look({ skin: 0xf2c9a5, hair: 0x6b2a4a, hairStyle: 'long', shirt: 0xe040a0, pants: 0x2b2b3a, accessory: 'none', age: 'young' }),
    arrive: { minRep: 20 },
    lines: {
      hello: '麥克風準備好了！',
      happy: ['今天大家唱到哭又唱到笑。', 'Joel 唱的情歌，全場安靜。'],
      unhappy: ['又被說太吵……', '包廂冷氣壞了。'],
      idle: ['要點什麼歌？印尼的、越南的、菲律賓的、泰國的都有。', '音量可以再大聲一點嗎？'],
      rival: ['唱歌又沒有錯。', '你很掃興耶。'],
      friend: ['幫你點一首。', '週日一起來唱！'],
      refuse: '這個租金，我要唱到天亮才付得起。',
    },
  }),
  T({
    id: 'zl-uncle', name: '五金行阿伯', shopName: '振興五金', shopType: 'grocery',
    traits: ['stubborn', 'veteran'], skill: 3, maxRentTier: 1,
    intro: '我在這條街開了四十年五金行。以前週日很安靜，現在……唉，人很多啦。',
    look: look({ skin: 0xe8b48f, hair: 0xd9d4cc, hairStyle: 'bald', shirt: 0x5b5f73, pants: 0x3d3a36, accessory: 'glasses', age: 'old' }),
    relations: { 'zl-lan': 20 },
    lines: {
      hello: '租就租，但機車不要停在我門口。',
      happy: ['今天賣了好多延長線，大家都要充電。', '那個菲律賓少年仔又來借螺絲起子。'],
      unhappy: ['機車又擋住我的門了！', '吵死了……'],
      idle: ['螺絲要幾號的？', '以前這條街很安靜啦。'],
      rival: ['你們不要坐在我店門口！', '垃圾自己帶走！'],
      friend: ['椅子拿去坐，記得還我。', '阿蘭，湯好喝。'],
      refuse: '這個租金，我做四十年都沒付過這麼多。',
    },
  }),
  T({
    id: 'zl-amy', name: '藥師 Amy', shopName: '安心藥局', shopType: 'pharmacy',
    traits: ['hardworking', 'shy'], skill: 4, maxRentTier: 1,
    intro: '很多移工生病了不敢去看醫生，怕講不通、怕被扣錢。我想做一間聽得懂大家的藥局。',
    look: look({ skin: 0xf6d6bd, hair: 0x2a1d17, hairStyle: 'bob', shirt: 0xf0f0f0, pants: 0x54627a, accessory: 'glasses', age: 'young' }),
    arrive: { minDay: 4 },
    lines: {
      hello: '有不舒服，一定要說喔。',
      happy: ['今天有人終於敢來看感冒了。', '多語的說明卡做好了！'],
      unhappy: ['有人拖到很嚴重才來……', '我的印尼話還不夠好。'],
      idle: ['一天三次，飯後吃。', 'Sakit di mana？哪裡痛？'],
      rival: ['身體比工作重要！', '……'],
      friend: ['這是維他命，送你。', '下次教我越南話。'],
      refuse: '這個租金，我的藥要賣得很貴……',
    },
  }),
];

// =====================================================================
// 劇情
// =====================================================================

const sunday = (c: { s: Parameters<typeof isSunday>[0] }) => isSunday(c.s);

const stories: StoryEvent[] = [
  {
    id: 'zl-intro', street: ST, once: true, priority: 100, when: 'morning',
    cond: (c) => (c.s.day === 1 ? {} : null),
    script: () => [
      narrate('桃園市中壢區・中壢車站前'),
      focus({ landmark: 'station' }),
      appear('zlChief', { landmark: 'station' }),
      appear('me', { landmark: 'station' }, -90),
      say('zlChief', '你就是會長喔？歡迎來中壢。這裡不是什麼老街，是車站前的舊商圈啦。'),
      say('zlChief', '平日都是趕火車的通勤族，很安靜。可是到了星期天……'),
      appear('zl-lan', { landmark: 'station' }, 90),
      say('zl-lan', '星期天，整條街會變成另一個國家喔！'),
      say('zl-lan', '印尼、越南、菲律賓、泰國的姊妹兄弟，一個禮拜只放一天假，有的只放半天。他們搭車來這裡，吃家鄉的菜、寄錢回家、跟家人視訊。'),
      say('zlChief', '人一多，機車停滿騎樓、坐滿地上、垃圾、吵……住這邊的人也很頭痛。'),
      emote('me', 'sweat'),
      say('zl-lan', '會長，我想在這裡開河粉店。還有，一定要有一間匯款行。大家最重要的事，就是把錢寄回家。'),
      narrate('週日人潮最多。每個國家的人都有「家鄉感」，吃到家鄉菜、匯到錢、跟家人視訊，下週就會帶更多同鄉來。'),
      narrate('每位移工頭上有收假時間。時間到了，就算排隊排到一半也得走。'),
      leave('zl-lan'), leave('zlChief'), leave('me'),
      effect({ applicant: ['zl-lan', 'zl-remit'], flag: ['intro'] }),
    ],
  },
  {
    id: 'zl-first-sunday', street: ST, once: true, priority: 90, when: 'noon',
    cond: (c) => (sunday(c) ? {} : null),
    script: () => [
      narrate('第一個星期天。'),
      focus({ landmark: 'plaza' }),
      appear('me', { landmark: 'plaza' }, -80),
      appear('zlChief', { landmark: 'plaza' }, 40),
      say('zlChief', '你看，廣場坐滿了人，騎樓停滿機車，地上……唉。'),
      appear('zlJoel', { landmark: 'plaza' }, 140),
      say('zlJoel', 'Sorry po！我們只是想找個地方坐。宿舍很小，十二個人一間。'),
      emote('me', 'idea'),
      narrate('點「站前廣場」可以決定週日的管法：嚴管、疏導、放任。'),
      narrate('嚴管：街坊不滿降得快，但大家會覺得被當成外人。疏導：要花錢，但兩邊都顧得到。放任：大家最自在，但街坊會越來越不滿。'),
      leave('zlJoel'), leave('zlChief'), leave('me'),
      effect({ flag: ['plazaPanel'] }),
    ],
  },
  {
    id: 'zl-siti', street: ST, once: true, priority: 85, when: 'noon',
    cond: (c) => (sunday(c) && c.s.day >= 8 && c.present.some((t) => c.shopOf(t)?.defId === 'remit') ? {} : null),
    script: () => [
      focus({ landmark: 'station' }),
      appear('zlSiti', { landmark: 'station' }),
      appear('me', { landmark: 'station' }, -90),
      say('zlSiti', '會長……匯款的隊伍好長。我三點就要回去了，阿嬤下午要吃藥。'),
      say('zlSiti', '這個月的錢，要寄回去給兒子繳學費。他今年上國中了。'),
      emote('zlSiti', 'sad'),
      choice('Siti 只剩一小時的假。要怎麼幫她？',
        opt('請匯款行週日加開窗口', { buff: { id: 'remitWindow', name: '匯款加開窗口', days: 30, mods: { shopAppeal: { remit: 1.3 } } }, flag: ['remitWindow'], homeFeel: { id: 5, vn: 3, ph: 3, th: 3 } }, [
          say('zlSiti', 'Terima kasih！以後大家都不用排那麼久了。'),
          emote('zlSiti', 'heart'),
        ], 4000),
        opt('讓她先插隊', { rep: -1, homeFeel: { id: 3 }, unrest: 3 }, [
          say('zlSiti', '謝謝……'),
          narrate('後面排隊的人不太開心，但也沒有人說什麼。大家都知道收假的滋味。'),
        ]),
        opt('我幫你代辦，收據下週拿給你', { rep: 2, homeFeel: { id: 4 } }, [
          say('zlSiti', '真的可以嗎？……謝謝你相信我，也謝謝你讓我相信你。'),
          emote('zlSiti', 'heart'),
        ]),
      ),
      narrate('Siti 往車站跑去。她頭上的時鐘，已經變紅了。'),
      leave('zlSiti'), leave('me'),
      effect({ flag: ['metSiti'] }),
    ],
  },
  {
    id: 'zl-missed-bus', street: ST, cooldown: 12, priority: 70, when: 'morning',
    cond: (c) => (c.flag('missedBus') ? {} : null),
    script: () => [
      narrate('昨天晚上，有人錯過了最後一班接駁車。'),
      focus({ landmark: 'factorybus' }),
      appear('zlNan', { landmark: 'factorybus' }),
      appear('me', { landmark: 'factorybus' }, -90),
      say('zlNan', '昨天唱歌唱太開心，跑過來的時候，車剛好開走了。'),
      say('zlNan', '我在廣場坐了一個晚上。今天早上要上工，不知道趕不趕得上……'),
      emote('zlNan', 'sweat'),
      choice('要怎麼幫他？',
        opt('幫他叫車趕回工廠', { rep: 1, homeFeel: { th: 3 } }, [
          say('zlNan', '謝謝會長！車錢我下週還你！'),
        ], 1200),
        opt('跟協會說，請工廠週日加開一班晚一點的車', { rep: 2, flag: ['lateBus'], homeFeel: { id: 2, vn: 2, ph: 2, th: 2 } }, [
          appear('zlSocial', { landmark: 'factorybus' }, 90),
          say('zlSocial', '我們去跟工廠談談看。很多人都是因為這樣被扣錢。'),
          leave('zlSocial'),
        ]),
      ),
      leave('zlNan'), leave('me'),
      effect({ unflag: ['missedBus'] }),
    ],
  },
  {
    id: 'zl-redline', street: ST, once: true, priority: 88, when: 'morning',
    cond: (c) => (c.flag('tried-strict') ? {} : null),
    script: () => [
      narrate('車站在大廳和廣場拉起了紅龍，貼上「禁止席地而坐」。'),
      focus({ landmark: 'plaza' }),
      appear('zlJoel', { landmark: 'plaza' }),
      appear('zl-lan', { landmark: 'plaza' }, 100),
      appear('me', { landmark: 'plaza' }, -90),
      say('zlJoel', '……所以我們連坐的地方都沒有了嗎？'),
      say('zl-lan', '網路上很多人在吵。有人說這樣比較整齊，也有人說這是在把人隔開。'),
      emote('zlJoel', 'sad'),
      choice('紅龍要怎麼處理？',
        opt('維持嚴管，紅龍留著', { rep: 1, unrest: -10, homeFeel: { id: -6, vn: -6, ph: -6, th: -6 } }, [
          say('zlJoel', '……我們知道了。'),
          narrate('廣場變得很整齊，也變得很安靜。'),
        ]),
        opt('拆掉紅龍，在廣場劃一塊正式的野餐區（改成疏導）', { rep: 2, policy: 'guide', unrest: -5, homeFeel: { id: 4, vn: 4, ph: 4, th: 4 } }, [
          say('zl-lan', '這樣大家有地方坐，也知道垃圾要丟哪裡！'),
          say('zlJoel', 'Salamat！我們會自己收乾淨的！'),
          emote('zlJoel', 'heart'),
        ], 5000),
      ),
      leave('zlJoel'), leave('zl-lan'), leave('me'),
    ],
  },
  {
    id: 'zl-petition', street: ST, cooldown: 6, priority: 75, when: 'morning',
    cond: (c) => (c.s.unrest >= 50 ? {} : null),
    script: () => [
      focus({ landmark: 'station' }),
      appear('zlChief', { landmark: 'station' }),
      appear('me', { landmark: 'station' }, -90),
      say('zlChief', '會長，住戶又來陳情了。說週日機車停到家門口、半夜還在唱歌、樓梯間都是垃圾。'),
      say('zlChief', '我知道他們不是故意的，可是住在這裡的人也要生活啊。'),
      emote('zlChief', 'sweat'),
      choice('要怎麼回應陳情？',
        opt('辦說明會，請各國的同鄉會代表一起來', { rep: 2, unrest: -12, homeFeel: { id: 2, vn: 2, ph: 2, th: 2 } }, [
          say('zlChief', '好主意。讓住戶跟他們面對面講，比我在中間傳話好。'),
          narrate('說明會上，印尼同鄉會的代表站起來說：「對不起，我們會自己排班打掃。」住戶阿姨愣了一下，點點頭。'),
          effect({ flag: ['townhall'] }),
        ], 2000),
        opt('先不理，週日的生意比較重要', { rep: -2, unrest: 5 }, [
          say('zlChief', '……你這樣，我很難做人耶。'),
        ]),
      ),
      leave('zlChief'), leave('me'),
    ],
  },
  {
    id: 'zl-uncle-joel', street: ST, once: true, priority: 80, when: 'noon',
    cond: (c) => (sunday(c) && c.has('zl-uncle') ? { a: 'zl-uncle' } : null),
    script: (b) => [
      focus(b.a),
      appear(b.a),
      appear('zlJoel', b.a, 120),
      say(b.a, '少年仔！你的機車又停在我門口！我要怎麼開門做生意！'),
      say('zlJoel', 'Sorry po, sorry！騎樓都停滿了……'),
      emote(b.a, 'anger'),
      narrate('Joel 牽車的時候，背上的吉他撞到柱子，一條弦斷了。'),
      emote('zlJoel', 'sad'),
      say(b.a, '……拿來。'),
      walk(b.a, 'zlJoel', -40),
      wait(500),
      say(b.a, '四十年的五金行，換一條弦而已。好了，試試看。'),
      fx('sparkle', 'zlJoel'),
      say('zlJoel', '……Salamat po，阿伯！我唱一首給你聽！'),
      emote(b.a, 'heart'),
      narrate('後來，阿伯的門口畫了一格機車停車格，寫著：「Joel 專用」。'),
      effect({ sat: [[b.a, 15]], rep: 2, flag: ['uncleJoel'], unrest: -8, homeFeel: { ph: 5 } }),
      leave('zlJoel'), leave(b.a),
    ],
  },
  {
    id: 'zl-pharmacy', street: ST, once: true, priority: 72, when: 'noon',
    cond: (c) => (c.has('zl-amy') ? { a: 'zl-amy' } : null),
    script: (b) => [
      focus(b.a),
      appear(b.a),
      appear('me', b.a, -90),
      say(b.a, '會長，昨天有一位越南大哥發燒了三天才來。他說怕看醫生講不通，又怕請假被扣錢。'),
      say(b.a, '我想做多國語言的用藥說明卡，再請阿蘭姐、Dewi 姐週日來幫忙翻譯。'),
      choice('要支持多語藥局嗎？',
        opt('支持！印說明卡、請翻譯志工', { buff: { id: 'multiPharm', name: '多語藥局', days: 30, mods: { shopAppeal: { pharmacy: 1.5 } } }, rep: 2, flag: ['multiPharm'], homeFeel: { id: 3, vn: 3, ph: 3, th: 3 } }, [
          say(b.a, '謝謝！這樣大家生病就比較敢來了。'),
          emote(b.a, 'heart'),
        ], 4000),
        opt('先等等', {}),
      ),
      leave(b.a), leave('me'),
    ],
  },
  {
    id: 'zl-ramadan', street: ST, once: true, priority: 78, when: 'morning',
    cond: (c) => (c.s.day >= 8 && c.has('zl-dewi') ? { a: 'zl-dewi' } : null),
    script: (b) => [
      narrate('齋戒月到了。'),
      focus(b.a),
      appear(b.a),
      appear('me', b.a, -90),
      say(b.a, '這一個月，穆斯林從日出到日落都不能吃東西、不能喝水。'),
      say(b.a, '妹妹們照樣要工作、要照顧阿公阿嬤、要在工廠搬貨。到了傍晚，大家都好想一起吃一頓飯。'),
      choice('要辦「開齋晚餐」嗎？',
        opt('辦！每天傍晚在廣場一起開齋', { flag: ['bukaPuasa'], homeFeel: { id: 8 } }, [
          say(b.a, 'Alhamdulillah！大家會很開心的！'),
          emote(b.a, 'heart'),
          narrate('傍晚，太陽下山的那一刻，廣場上一起響起「Selamat berbuka！」'),
        ], 3000),
        opt('心意到就好', {}, [say(b.a, '好，謝謝會長。')]),
      ),
      say(b.a, '齋戒月結束，就是開齋節。那是我們最大的節日，像你們的過年一樣。'),
      narrate('解鎖活動：開齋節！（在「活動」裡舉辦）'),
      effect({ unlockActivity: ['templeFair'] }),
      leave(b.a), leave('me'),
    ],
  },
  {
    id: 'zl-runaway', street: ST, once: true, priority: 68, when: 'noon',
    cond: (c) => (c.s.day >= 10 ? {} : null),
    script: () => [
      focus({ landmark: 'church' }),
      appear('zlSocial', { landmark: 'church' }),
      appear('me', { landmark: 'church' }, -90),
      say('zlSocial', '會長，有件事想請你幫忙。'),
      say('zlSocial', '有一位越南的小兄弟，來台灣的時候借了很多錢付仲介費，現在每個月薪水被扣一大半，還被叫去做合約上沒有的工作。'),
      say('zlSocial', '他說他想逃跑。可是逃跑之後就是「失聯移工」，沒有健保、隨時會被抓，處境只會更糟。'),
      emote('me', 'sad'),
      choice('要怎麼幫他？',
        opt('陪他去勞工局申訴，申請轉換雇主', { rep: 3, flag: ['helpedTransfer'], homeFeel: { vn: 6, id: 2, ph: 2, th: 2 } }, [
          say('zlSocial', '好。有人陪著，他就比較敢說了。'),
          narrate('三個禮拜後，他轉到一間新的工廠。週日，他第一次來阿蘭的店吃河粉。'),
        ]),
        opt('捐錢給移工協會的法律扶助', { rep: 2, flag: ['donatedNgo'], homeFeel: { id: 3, vn: 3, ph: 3, th: 3 } }, [
          say('zlSocial', '謝謝。這筆錢可以幫到不只一個人。'),
        ], 6000),
      ),
      leave('zlSocial'), leave('me'),
    ],
  },
  {
    id: 'zl-nan-dream', street: ST, once: true, priority: 66, when: 'morning',
    cond: (c) => (c.s.day >= 5 ? {} : null),
    script: () => [
      focus({ landmark: 'factorybus' }),
      appear('zlNan', { landmark: 'factorybus' }),
      appear('me', { landmark: 'factorybus' }, -90),
      say('zlNan', '會長，我在工地做了十二年，合約快到期了。'),
      say('zlNan', '我太太是台灣人，我們想留下來。每個週日我都在宿舍煮菜給大家吃，大家說我應該開店。'),
      say('zlNan', '這條街……還沒有泰國菜。'),
      emote('me', 'idea'),
      narrate('阿南出現在招租佈告欄上了。'),
      effect({ flag: ['nanDream'], applicant: ['zl-nan'] }),
      leave('zlNan'), leave('me'),
    ],
  },
  {
    id: 'zl-songkran', street: ST, once: true, priority: 64, when: 'noon',
    cond: (c) => (sunday(c) && c.has('zl-nan') ? { a: 'zl-nan' } : null),
    script: (b) => [
      narrate('四月，泰國新年——潑水節。'),
      focus({ landmark: 'plaza' }),
      appear(b.a, { landmark: 'plaza' }),
      appear('me', { landmark: 'plaza' }, -90),
      say(b.a, 'สุขสันต์วันสงกรานต์！新年快樂！潑水是祝福喔！'),
      fx('confetti', b.a),
      narrate('廣場上水花四濺。路過的通勤族嚇了一跳，被潑到的阿伯先是大罵，後來自己也拿起水桶。'),
      emote('me', 'shock'),
      effect({ buff: { id: 'songkran', name: '潑水節', days: 1, mods: { traffic: 1.2, appeal: { food: 1.2 } } }, rep: 1, homeFeel: { th: 8 }, unrest: 4 }),
      leave(b.a), leave('me'),
    ],
  },
  {
    id: 'zl-mass', street: ST, once: true, priority: 62, when: 'morning',
    cond: (c) => (sunday(c) && c.s.homeFeel.ph >= 45 ? {} : null),
    script: () => [
      narrate('星期天早上，天主堂的鐘聲響了。'),
      focus({ landmark: 'church' }),
      appear('zlJoel', { landmark: 'church' }),
      appear('me', { landmark: 'church' }, -90),
      say('zlJoel', '彌撒結束後，大家都會留下來一起吃東西。神父說，這裡就是我們在台灣的家。'),
      say('zlJoel', '我們排了值日生，吃完自己把教堂前面掃乾淨。'),
      emote('zlJoel', 'music'),
      narrate('亂中自有秩序：家鄉感高的社群，會自己組織起來，街坊不滿也會慢慢降下來。'),
      effect({ rep: 2, homeFeel: { ph: 5 }, unrest: -5 }),
      leave('zlJoel'), leave('me'),
    ],
  },
  {
    id: 'zl-tet', street: ST, once: true, priority: 60, when: 'morning',
    cond: (c) => (c.has('zl-lan') && c.s.day >= 14 ? { a: 'zl-lan' } : null),
    script: (b) => [
      narrate('越南新年到了。'),
      focus(b.a),
      appear(b.a),
      appear('zl-uncle', b.a, 110),
      appear('me', b.a, -90),
      say(b.a, '我包了一百顆粽子（bánh chưng），請整條街吃！'),
      say('zl-uncle', '……這個粽子怎麼是方的？'),
      say(b.a, '越南的粽子是方的，代表大地。阿伯，吃吃看。'),
      say('zl-uncle', '……嗯。好吃。'),
      emote('zl-uncle', 'heart'),
      narrate('那天，住戶、店家、移工，一起站在騎樓下吃方形的粽子。'),
      effect({ rep: 2, flag: ['tet'], homeFeel: { vn: 6 }, unrest: -10 }),
      leave('zl-uncle'), leave(b.a), leave('me'),
    ],
  },
  {
    id: 'zl-self-order', street: ST, once: true, priority: 58, when: 'evening',
    cond: (c) => (sunday(c) && selfOrder(c.s) >= 0.3 ? {} : null),
    script: () => [
      narrate('星期天傍晚，人潮開始往車站走。'),
      focus({ landmark: 'plaza' }),
      appear('zl-dewi', { landmark: 'plaza' }),
      appear('zlJoel', { landmark: 'plaza' }, 90),
      appear('zlChief', { landmark: 'plaza' }, -100),
      narrate('廣場上，各國的同鄉會拿出垃圾袋，一區一區地撿。機車一台一台牽到停車格。'),
      say('zlChief', '……我當里長二十年，第一次看到星期天晚上的廣場這麼乾淨。'),
      say('zl-dewi', '因為這裡也是我們的地方啊。'),
      emote('zlChief', 'heart'),
      narrate('亂中自有秩序。'),
      effect({ rep: 3, flag: ['selfOrder'], unrest: -10 }),
      leave('zlJoel'), leave('zl-dewi'), leave('zlChief'),
    ],
  },
  {
    id: 'zl-ending', street: ST, once: true, priority: 99, when: 'evening',
    cond: (c) => (c.street.goals.every((g) => g.check(c.s)) ? {} : null),
    script: () => [
      narrate('開齋節過後的那個星期天。'),
      focus({ landmark: 'plaza' }),
      appear('me', { landmark: 'plaza' }, -60),
      appear('zl-lan', { landmark: 'plaza' }, 20),
      appear('zl-dewi', { landmark: 'plaza' }, 90),
      appear('zlJoel', { landmark: 'plaza' }, 160),
      appear('zlNan', { landmark: 'plaza' }, -140),
      say('zl-dewi', '會長，今天大家帶了自己家鄉的菜，一起在廣場野餐！'),
      appear('zl-uncle', { landmark: 'plaza' }, 220),
      say('zl-uncle', '椅子不夠啦，我店裡的全部搬出來了。'),
      appear('zlSiti', { landmark: 'plaza' }, -200),
      appear('zlGrandma', { landmark: 'plaza' }, -240),
      say('zlSiti', '雇主說，今天我可以放一整天假。阿嬤說她也想來。'),
      say('zlGrandma', '……這個，好吃。妳煮的？'),
      say('zlSiti', '對，阿嬤。這是我們印尼的菜。'),
      emote('zlGrandma', 'heart'),
      emote('zlSiti', 'heart'),
      say('zlJoel', '大家，我寫了一首歌。'),
      emote('zlJoel', 'music'),
      narrate('河粉、沙爹、打拋豬、菲律賓炸香蕉，還有阿伯從家裡帶來的滷肉。廣場上，四種語言、加上台語和國語，一起笑成一團。'),
      fx('confetti', 'me'),
      narrate('傍晚，大家一起往車站走。有人趕接駁車，有人陪阿嬤慢慢走。'),
      narrate('月台上，阿蘭貼了一張紙。上面寫著——'),
      narrate('「Sampai jumpa minggu depan・Hẹn gặp lại tuần sau・Kita-kits next week・เจอกันอาทิตย์หน้า・下週見」'),
      emote('me', 'star'),
      narrate('中壢東南亞街完成！'),
      effect({ chapterComplete: true }),
      leave('zlGrandma'), leave('zlSiti'), leave('zl-uncle'), leave('zlNan'), leave('zlJoel'), leave('zl-dewi'), leave('zl-lan'), leave('me'),
    ],
  },
];

// =====================================================================
// 老街資料
// =====================================================================

export const FEEL_GOAL = 70;
export const REVENUE_GOAL = 2_000_000;

export const ZHONGLI: StreetDef = {
  id: ST,
  name: '中壢東南亞街',
  region: '桃園市中壢區',
  difficulty: 3,
  tagline: '車站前・一週一天的家鄉',
  intro: '這裡不是景點，是車站前的舊商圈。平日是通勤族匆匆走過；到了星期天，整條街會突然變成另一個國家——印尼、越南、菲律賓、泰國的移工，一週只放一天假，搭車來這裡吃家鄉菜、寄錢回家、跟家人視訊。人很多、很吵、很亂，但亂中自有秩序。',
  map: { x: 0.6, y: 0.2 },
  playable: true,
  facade: 'stationfront',
  backdrop: 'city-rail',
  ground: 'arcade',
  layout: [
    { kind: 'landmark', id: 'station' },
    { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' },
    { kind: 'landmark', id: 'plaza' },
    { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' },
    { kind: 'landmark', id: 'church' },
    { kind: 'lot' }, { kind: 'lot' }, { kind: 'lot' },
    { kind: 'landmark', id: 'factorybus' },
  ],
  landmarks: [
    { id: 'station', name: '中壢車站', description: '週日一早，火車一班一班進站，整條街的人從這裡湧出來；收假時間到了，大家又往這裡跑。', width: 320 },
    { id: 'plaza', name: '站前廣場', description: '週日大家席地而坐、野餐、聊天的地方。點這裡可以決定週日的管法。', width: 340 },
    { id: 'church', name: '天主堂', description: '週日上午，菲律賓移工來望彌撒；彌撒後教堂前會有攤販。（實際上離車站有一段路）', width: 260 },
    { id: 'factorybus', name: '工廠接駁車站', description: '工廠宿舍的接駁車。晚上 9 點最後一班，錯過就回不去了。', width: 280 },
  ],
  startLots: 4,
  startMoney: 30000,
  startRep: 10,
  baseTraffic: 8,
  repTraffic: 0.25,
  weekendMult: 1,
  rentMult: 0.9,
  maintenance: 300,
  lotCost: 6000,
  closeHour: 23,
  weather: { rain: 0.2, fog: 0 },
  visitors: { jp: 0, kr: 0 },
  migrant: { id: 70, vn: 50, ph: 38, th: 30 },
  shopTypes: ['warung', 'pho', 'sarisari', 'thaifood', 'remit', 'phoneshop', 'asiamart', 'ktv', 'grocery', 'pharmacy', 'cafe'],
  tenants,
  stories,
  activities: {
    templeFair: {
      name: '開齋節', temple: '廣場',
      desc: '齋戒月結束後，穆斯林最大的節日。廣場擠滿上萬人一起禱告、吃東西、拍照。印尼移工 ×2、其他國家 ×1.2，秩序壓力最大的一天；印尼社群的家鄉感大幅上升。',
    },
    mascots: [
      { id: 'zlScooter', name: '機車騎士阿弟', description: '一台會走路的機車，提醒大家停進停車格。街坊不滿比較不會累積（人潮 +5%）。', mods: { traffic: 1.05, repPerDay: 0.2 } },
      { id: 'zlBowl', name: '河粉碗公', description: '一碗冒著熱氣的河粉，誰看到都餓。吃的店 +12%。', mods: { appeal: { food: 1.12 } } },
      { id: 'zlPhone', name: '視訊小手機', description: '螢幕上一直在跟家人揮手的小手機。手機行、匯款行 +20%。', mods: { shopAppeal: { phoneshop: 1.2, remit: 1.2 } } },
    ],
    legends: [
      { id: 'lucky', name: '在這條街寄的錢，會平安到家', description: '溫和可信，幾乎不會出事。匯款行 +25%。', risk: 0.05, mods: { shopAppeal: { remit: 1.25 } } },
      { id: 'taste', name: '吃到家鄉味，就不會想家想到哭', description: '有點誇張，可能被拆穿。吃的店 +20%。', risk: 0.3, mods: { appeal: { food: 1.2 } } },
    ],
  },
  goals: [
    { id: 'feel', text: `印尼、越南、菲律賓、泰國的家鄉感都達到 ${FEEL_GOAL}`, check: (s) => homeFeelOk(s, FEEL_GOAL) },
    { id: 'sunday', text: '一個超過 1,200 人的週日，街坊不滿低於 30', check: (s) => s.flags.includes('goodSunday') },
    { id: 'lebaran', text: '舉辦開齋節', check: (s) => s.flags.includes('held-templeFair') },
    { id: 'revenue', text: '老街累積營收 $2,000,000', check: (s) => s.totalRevenue >= REVENUE_GOAL },
  ],
};
